<div class="row">
    <div class="col-xs-10">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-align-justify"></i></span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add new area">
                    <a href="area-add.php" style="color: white;">Add</a>
                </span>
            </div>
            <div class="widget-content">
                <table class="table table-bordered table-striped table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>SL</th>
                            <th>Name</th>
                            <th>Action</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i=0;?>
                        <?php foreach($areas as $d):?>
                        <tr>
                            <td><?php echo ++$i;?>.</td>
                            <td><?php echo $d['name'];?></td>
                            <td class="text-right">
                                <a href="<?php echo BASE_URL.'/operation/area-update.php?id='.$d['id'];?>" class="text-primary"><i class="fa fa-edit"></i> Edit</a>
                            </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>							
            </div>
        </div>
    </div>
</div>

<?php 
//Utility::pr($packages);