
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Back to Building List Page">
                    <a href="building.php" style="color: white;">Building List</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="" name="user_inpt_frm" id="user_inpt_frm">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="area">Area</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['area'])){echo ' has-error';}?>">
                            <select name="area" id="area" class="form-control input-sm">
                                <option value=""></option>
                                <?php foreach($areas as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$area){echo 'selected';}?>><?php echo $val;?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['area'])):?><span class="help-inline" for="area"><?php echo $errors['area'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="building">Building</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['building'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="building" id="building" value="<?php echo $building;?>" placeholder="Building" autocomplete="off" />
                            <?php if(isset($errors['building'])):?><span class="help-inline" for="building"><?php echo $errors['building'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="router">Router</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['router'])){echo ' has-error';}?>">
                            <select name="router" id="router" class="form-control input-sm">
                                <option value=""></option>
                                <?php foreach($mikrotik_routers as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$router){echo 'selected';}?>><?php echo $val['router_name'];?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['router'])):?><span class="help-inline" for="router_no"><?php echo $errors['router'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="local_ip">Local IP</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['local_ip'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="local_ip" id="local_ip" value="<?php echo $local_ip;?>" placeholder="Local IP" autocomplete="off" readonly />
                            <?php if(isset($errors['local_ip'])):?><span class="help-inline" for="local_ip"><?php echo $errors['local_ip'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="ip_block">IP Block</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['ip_block'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="ip_block" id="ip_block" value="<?php echo $ip_block;?>" placeholder="IP Block" autocomplete="off" readonly />
                            <?php if(isset($errors['ip_block'])):?><span class="help-inline" for="ip_block"><?php echo $errors['ip_block'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="remote_ip_first">First Remote IP</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['remote_ip_first'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="remote_ip_first" id="remote_ip_first" value="<?php echo $remote_ip_first;?>" placeholder="First Remote IP" autocomplete="off" readonly />
                            <?php if(isset($errors['remote_ip_first'])):?><span class="help-inline" for="remote_ip_first"><?php echo $errors['remote_ip_first'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="remote_ip_last">Last Remote IP</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['remote_ip_last'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="remote_ip_last" id="remote_ip_last" value="<?php echo $remote_ip_last;?>" placeholder="Last Remote IP" autocomplete="off" readonly />
                            <?php if(isset($errors['remote_ip_last'])):?><span class="help-inline" for="remote_ip_last"><?php echo $errors['remote_ip_last'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Update" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
