<div class="row">

	<div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5>Search</h5>
            </div>
            <div class="widget-content nopadding">
                <form action="delete-inactive-subscribers.php" method="get">
                <div class="row" style="font-size:.8em; margin-bottom: 20px;">
                    <div class="col-md-2">
                        Days:
                        <input type="text" id="days" name="days" value="<?php echo $days;?>" class="form-control input-sm" />
                    </div>
                    <div class="col-md-4">
                        Router:<br>
                        <select name="rn" id="rn">
                            <?php foreach($mikrotik_routers as $key=>$val):?>
                            <option value="<?php echo $key?>"<?php if($key==$router_no) echo ' selected';?>><?php echo $val['router_name'];?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        &nbsp;<br>
                        <button class="btn btn-success btn-sm"><span class="icon"><i class="fa fa-search"></i> </span> Search</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>

    <?php if(count($data) > 0):?>
	<div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>                                    
                </span>
                <h5>Inactive Subscribers
                <?php if(!empty($data)){ echo ' (Total '.$total.' records found)';}?>
                </h5>
            </div>
            <div class="widget-content nopadding">
            	<form action="delete-inactive-subscribers.php?days=<?php echo $days;?>&rn=<?php echo $router_no;?>" method="post">
            	<button class="btn btn-success btn-sm"><span class="icon"> Delete Selected Subscribers</button>
                <table id="inctv-subs" class="table table-bordered table-striped table-hover" style="border-top:#229955 solid 1px;">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="checkall" /></th>
                            <th>Login ID</th>
                            <th>Rank</th>
                            <th>Name</th>
                            <th>Address (House, Building, Area)</th>
                            <th>Router</th>
                            <th>Inactive Days</th>
                        </tr>
                    </thead>
                    <tbody>
                    	<?php $i=0;?>
                        <?php foreach ($data as $d): ?>
                            <tr>
                                <td class="text-right">
	                                <input type="checkbox" name="uname[]" value="<?php echo $d['username']; ?>" />
	                                <?php echo $limit*($page-1) + ++$i;?>.
                                </td>
                                <td><?php echo $d['username']; ?></td>
                                <td><?php echo $d['rank']; ?></td>
                                <td><?php echo trim($d['firstname'].' '.$d['lastname']); ?></td>
                                <td><?php echo $d['house_no'].', '.$d['building'].', '.$d['area']; ?></td>
                                <td><?php echo isset($mikrotik_routers[$d['router_no']]['router_name']) ? $mikrotik_routers[$d['router_no']]['router_name'] : '?'; ?></td>
                                <td class="text-right"><?php echo $d['inactive_days']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                </form>
                <?php echo $paginationStr;?>
            </div>
        </div>
    </div>
    <?php endif;?>
</div>


<script type="text/javascript">
$(document).ready(function() {
  $('#checkall').click(function() {
    var checked = $(this).prop('checked');
    $('#inctv-subs').find('input:checkbox').prop('checked', checked);
  });
})
</script>