
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5>Create New User</h5>
                <a class="btn btn-primary btn-xs" href="package-index.php" style="margin-top: 5px; margin-right: 5px; float:right;">&laquo; Back to List Packages</a>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="package-update.php?id=<?php echo $id;?>" name="package_add_frm" id="package_add_frm">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="code">Code</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['code'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="code" id="code" value="<?php echo $code;?>" placeholder="Code" autocomplete="off" />
                            <?php if(isset($errors['code'])):?><span class="help-inline" for="code"><?php echo $errors['code'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="name">Name</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['name'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="name" id="name" value="<?php echo $name;?>" placeholder="Name" autocomplete="off" />
                            <?php if(isset($errors['name'])):?><span class="help-inline" for="name"><?php echo $errors['name'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="mb_unit_value">Value in mbps</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['mb_unit_value'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="mb_unit_value" id="mb_unit_value" value="<?php echo $mb_unit_value;?>" placeholder="Enter equlivalent value in mbps" autocomplete="off" />
                            <?php if(isset($errors['mb_unit_value'])):?><span class="help-inline" for="mb_unit_value"><?php echo $errors['mb_unit_value'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="price">Price</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['price'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="price" id="code" value="<?php echo $price;?>" placeholder="Price" autocomplete="off" />
                            <?php if(isset($errors['price'])):?><span class="help-inline" for="price"><?php echo $errors['price'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="days">Days</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['days'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="days" id="code" value="<?php echo $days;?>" placeholder="Days" autocomplete="off" />
                            <?php if(isset($errors['days'])):?><span class="help-inline" for="days"><?php echo $errors['days'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Update" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
