<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5><h5><?php echo $pageTitle;?></h5></h5>
            </div>
            <div class="widget-content nopadding">
                
                <form action="" method="get">
                <div class="row" style="font-size:.8em; margin-bottom: 20px;">
                    <div class="col-md-4">
                        Date from:
                        <input type="text" data-date="<?php echo $date_from;?>" data-date-format="dd-mm-yyyy" id="date_from" name="date_from" value="<?php echo $date_from;?>" class="datepicker form-control input-sm" />
                    </div>
                    <div class="col-md-4">
                        Date to:
                        <input type="text" data-date="<?php echo $date_to;?>" data-date-format="dd-mm-yyyy" id="date_to" name="date_to"  value="<?php echo $date_to;?>" class="datepicker form-control input-sm" />
                    </div>
                    <div class="col-md-2">
                        &nbsp;<br>
                        <button class="btn btn-success btn-sm">Search</button>
                    </div>
                </div>
                </form>
                
                <?php if(!empty($result)):?>
                <div class="row">
                    <?php
                        $tot_free_bandwidth = 0;
                        $tot_paid_bandwidth = 0;
                        $tot_total_bandwidth = 0;
                    ?>
                    <table class="table table-bordered table-striped table-hover data-table">
                        <thead>
                            <tr style="border-top:1px solid #D9D9D9;">
                                <th rowspan="2">SL #</th>
                                <th rowspan="2">Username</th>
                                <th rowspan="2">Name</th>
                                <th rowspan="2">Category</th>
                                <th colspan="3">Bandwidth (Mbps)</th>
                                <th rowspan="2">Ratio Factor</th> 
                                <th rowspan="2">Connection From</th>                            
                            </tr>
                            <tr style="border-top:1px solid #D9D9D9;">
                                <th>Free</th>
                                <th>Paid</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody style="font-size:.95em;">
                        <?php $i=0;?>
                        <?php foreach($result as $res):?>
                        <?php
                        $tot_free_bandwidth += $res['free_bandwidth'];
                        $tot_paid_bandwidth += $res['paid_bandwidth'];
                        $tot_total_bandwidth += $res['total_bandwidth'];
                        ?>
                        <tr>
                            <td class=""><?php echo ++$i;?>.</td>
                            <td><?php echo $res['username'];?></td>
                            <td><?php echo trim($res['firstname'].' '.$res['lastname']);?></td>
                            <td><?php echo $res['category'];?></td>
                            <td class="text-right"><?php echo number_format((float)$res['free_bandwidth'], 2, '.', '');?></td>
                            <td class="text-right"><?php echo number_format((float)$res['paid_bandwidth'], 2, '.', '');?></td>
                            <td class="text-right"><?php echo number_format((float)$res['total_bandwidth'], 2, '.', '');?></td>
                            <td class="text-right text-muted"><?php echo $res['complemtntary_ratio_factor'];?></td>
                            <?php /*?>
                            <td class="text-right"><?php echo $res['free_bandwidth'];?></td>
                            <td class="text-right"><?php echo $res['paid_bandwidth'];?></td>
                            <td class="text-right"><?php echo $res['total_bandwidth'];?></td>
                            <?php */?>
                            <td class="text-muted"><?php echo Date::niceDateTime($res['connection_from']);?></td>
                        </tr>
                        <?php endforeach;?>
                        
                        <tr>
                            <td colspan="4" class="text-right" style="background-color: #CFF0BF;"><b>Total Bandwidth (Mbps)</b></td>
                            <td class="text-right" style="background-color: #CFF0BF;"><b><?php echo number_format((float)$tot_free_bandwidth, 2, '.', '');?></b><br /> <i>(Free)</i></td>
                            <td class="text-right" style="background-color: #CFF0BF;"><b><?php echo number_format((float)$tot_paid_bandwidth, 2, '.', '');?></b><br /> <i>(Paid)</i></td>
                            <td class="text-right" style="background-color: #CFF0BF;"><b><?php echo number_format((float)$tot_total_bandwidth, 2, '.', '');?></b><br /> <i>(Total)</i></td>
                            <td colspan="2" style="background-color: #CFF0BF;">&nbsp;</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <?php endif;?>
            </div>
        </div>
    </div>
    
    
</div>

<?php //echo '<pre>'.$sql;?>