<?php //Utility::pa($data);?>

<div class="row">
    <div class="col-xs-8">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-th-list"></i></span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add New Bank Deposit">
                    <a href="bank-deposit-add.php" style="color: white;">Add New Bank Deposit</a>
                </span>
            </div>
            <div class="widget-content">
                <table class="table table-bordered table-striped table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Amount (<?php echo CURRENCY;?>)</th>
                            <th>Date</th>
                            <th>Submitted by</th>
                            <th>Purpose</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i=0;?>
                        <?php foreach($data as $d):?>
                        <tr>
                            <td><?php echo ++$i;?>.</td>
                            <td class="text-right"><?php echo Utility::commaSeperator($d['amount'],2);?></td>
                            <td><?php echo Date::niceDate($d['date']);?></td>
                            <td><?php echo trim($d['firstname'].' '.$d['lastname']);?></td>
                            <td><?php echo $d['purpose'];?></td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>							
            </div>
        </div>
    </div>
</div>