<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
            </div>
            <div class="widget-content nopadding">
                <form action="disconnect-report.php" method="get">
                <div class="row" style="font-size:.8em; margin-bottom: 0px;">
                    <div class="col-md-2">
                        Date:
                        <input type="text" data-date="<?php echo $date;?>" data-date-format="dd-mm-yyyy" id="date" name="date" value="<?php echo $date;?>" class="datepicker form-control input-sm" />
                    </div>
                    &nbsp;<br>
                    <button class="btn btn-success btn-sm"><span class="icon"><i class="fa fa-search"></i> </span> Search</button>
                </div>
                </form>
                
                <?php if(!empty($data)):?>
                <div class="row">
                    <table class="table table-bordered table-striped table-hover data-table">
                        <thead>
                            <tr style="border-top:1px solid #D9D9D9;">
                                <th>SL</th>
                                <th>Username</th>
                                <th>Rank</th>
                                <th>Fullname</th>
                                <th>Address (House, Building, Area)</th>
                                <th>Router</th>
                                <th>Disconnected</th>                            
                            </tr>
                        </thead>
                        <tbody style="font-size:.95em;">
                        <?php $i=0;?>
                        <?php foreach($data as $key=>$val):?>
                        <tr>
                            <td class=""><?php $sl = ($page-1)*LIMIT_PER_PAGE + ++$i; echo $sl;?>.</td>
                            <td><?php echo $val['username'];?></td>
                            <td><?php echo $val['rank'];?></td>
                            <td><?php echo trim($val['firstname'].' '.$val['lastname']);?></td>
                            <td><?php echo $val['house_no'].', '.$val['building'].', '.$val['area'];?></td>
                            <td><?php echo isset($mikrotik_routers[$val['router_no']]['router_name']) ? $mikrotik_routers[$val['router_no']]['router_name'] : '';?></td>
                            <td><?php echo Date::niceDateTime5($val['disconneted_at']);?></td>
                        </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>


<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area.php',
            data : {id: $(this).val()},
            success : function (msg) {
                        $('#bld').html(msg);
                    }
        });
    });
});
</script>