<div class="row">
    <div class="col-xs-7">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
<!--                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add New Subscriber">
                    <a href="add.php" style="color: white;">Add</a>
                </span>-->
            </div>
            <div class="widget-content nopadding">
                <form action="payment-history.php" method="get">
                <div class="row" style="font-size:.8em; margin-bottom: 20px;">
                    <div class="col-md-4">
                        Username:
                        <input type="text" id="username" name="username" value="<?php echo $username;?>" class="form-control input-sm" />
                    </div>
                    <div class="col-md-2">
                        <br>
                        <button class="btn btn-success btn-sm">Search</button>
                    </div>
                </div>
                </form>
                <div class="row">
                <?php if(empty($data)):?>
                <!--<p><h4 class="text-center">No payment record found!</h4></p>-->
                <?php else:?>
                <table class="table table-bordered table-striped table-hover" style="border-top:#229955 solid 1px;">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Debit (<?php echo CURRENCY;?>)</th>
                            <th>Credit (<?php echo CURRENCY;?>)</th>
                            <th>Balance (<?php echo CURRENCY;?>)</th>
                            <th>Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data as $d): ?>
                            <tr>
                                <td class="b"><?php echo $d['type']; ?></td>
                                <td class="text-right"><?php echo Utility::thousandSeperator($d['debit']); ?></td>
                                <td class="text-right"><?php echo Utility::thousandSeperator($d['credit']); ?></td>
                                <td class="text-right"><?php echo Utility::thousandSeperator($d['balance']); ?></td>
                                <td><?php echo Date::niceDateTime($d['created_at']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>