<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5>Revenue and Bank Deposit Report</h5>
            </div>
            <div class="widget-content nopadding">
                <form action="revenue.php" method="get">
                <div class="row" style="font-size:.8em; margin-bottom: 20px;">
                    <div class="col-md-4">
                        Date from:
                        <input type="text" data-date="<?php echo $date_from;?>" data-date-format="dd-mm-yyyy" id="date_from" name="date_from" value="<?php echo $date_from;?>" class="datepicker form-control input-sm" />
                    </div>
                    <div class="col-md-4">
                        Date to:
                        <input type="text" data-date="<?php echo $date_to;?>" data-date-format="dd-mm-yyyy" id="date_to" name="date_to"  value="<?php echo $date_to;?>" class="datepicker form-control input-sm" />
                    </div>
                    <div class="col-md-2">
                        &nbsp;<br>
                        <button class="btn btn-success btn-sm">Search</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5>Revenue</h5>
            </div>
            <div class="widget-content nopadding">
                <!-- <div class="row">
                    <div class="col-md-6">
                        Total cards: <strong><?php echo $total_cards;?></strong>
                    </div>
                    <div class="col-md-6">
                        Total amount: <strong><?php echo Utility::commaSeperator($total_amount) . ' '. CURRENCY;?></strong>
                    </div>
                </div> -->
                <?php if(!empty($revenue)):?>
                <div class="row">
                    <table class="table table-bordered table-striped table-hover data-table">
                        <thead>
                            <tr style="border-top:1px solid #D9D9D9;">
                                <th>SL#</th>
                                <th>Date</th>
                                <th>Details</th>
                                <th>Amount (<?php echo CURRENCY;?>)</th>
                            </tr>
                        </thead>
                        <tbody style="font-size:.95em;">
                        <?php $i=0;?>
                        <?php foreach($revenue as $key=>$val):?>
                        <tr>
                            <td class="text-right"><?php echo ($page-1)*$limit + ++$i;?>.</td>
                            <td><?php echo Date::niceDateTime($val['date']);?></td>
                            <td><?php 
                                if($val['type']=='Scratch Card'){
                                    echo "Scratch Card (<b>Subscriber:</b> {$val['username']} <b>Card:</b> {$val['scratch_card']})";
                                } elseif($val['type']=='Corporate Payment'){
                                    echo $val['comment']." (<b>Name:</b> {$val['firstname']})";
                                }
                            ?></td>
                            <td class="text-right"><?php echo Utility::commaSeperator($val['amount']);?></td>
                        </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
					<?php echo $paginationStr;?>
                </div>
                <?php endif;?>
            </div>
        </div>
    </div>
    
    <div class="col-sm-4">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>                                    
                </span>
                <h5>Revenue Summary</h5>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered table-striped table-condensed table-hover">
                    <tr>
                        <td>Scratch-Card Amount</td>
                        <td class="text-right"><?php echo Utility::commaSeperator($card_amount);?> <?php echo CURRENCY;?></td>
                    </tr>
                    <tr>
                        <td>Corporate Amount</td>
                        <td class="text-right"><?php echo Utility::commaSeperator($corporate_amount);?> <?php echo CURRENCY;?></td>
                    </tr>
                    <tr>
                        <td>Total Amount</td>
                        <td class="text-right"><?php echo Utility::commaSeperator($total_amount);?> <?php echo CURRENCY;?></td>
                    </tr>
                    <tr>
                        <td>Total cards Sold</td>
                        <td class="text-right"><?php echo Utility::commaSeperator($total_cards);?></td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5>Bank Deposit</h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add New Bank Deposit">
                    <a href="bank-deposit-add.php" style="color: white;">Add New Bank Deposit</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <div class="row" style="margin-bottom: 20px;">
                    <div class="col-md-6">Total deposit: <strong><?php echo Utility::commaSeperator($total_deposit) . ' '. CURRENCY;?></strong></div>
                </div>
                <?php if(!empty($deposit)):?>
                <table class="table table-bordered table-striped table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Date</th>
                            <th>Amount (<?php echo CURRENCY;?>)</th>
                            <th>Entry by</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i=0;?>
                        <?php foreach($deposit as $d):?>
                        <tr>
                            <td><?php echo ++$i;?>.</td>
                            <td><?php echo Date::niceDate($d['date']);?></td>
                            <td class="text-right"><?php echo Utility::commaSeperator($d['amount']);?></td>
                            <td><?php echo trim($d['firstname'].' '.$d['lastname']);?></td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>