<div id="user-nav">
			<div id="mobile-menu">
          		<a href="javascript:;" id="sidebar-mobile-menu">MENU</a>				
			</div>
            <ul class="btn-group">
                <li class="btn" ><a title="" href="<?php echo BASE_URL;?>/my-account.php"><i class="fa fa-user"></i> <span class="text"><?php echo Session::get('fullname');?></span></a></li>
                <li class="btn"><a title="" href="<?php echo BASE_URL;?>/change-password.php"><i class="fa fa-cog"></i> <span class="text">Change Password</span></a></li>
                <li class="btn"><a title="" href="<?php echo BASE_URL;?>/logout.php"><i class="fa fa-share"></i> <span class="text">Logout</span></a></li>
            </ul>
        </div>