            <div id="breadcrumb">
                <?php echo Utility::breadcrumbs('', $pageTitle);?>
			</div>
            <?php 
            $successMsg = Session::flash('success');
            $errorMsg = Session::flash('error');
            
            if(!empty($successMsg)){?>
            <div class="row">
                <div class="col-xs-12">
                    <div class="alert alert-success text-center">
                        <button class="close" data-dismiss="alert">×</button>
                        <strong><i class="fa fa-check-circle"></i> </strong> <?php echo $successMsg;?>
                    </div>
                </div>
            </div>
            <?php }
            else if(!empty($errorMsg)){?>
            <div class="row">
                <div class="col-xs-12">
                    <div class="alert alert-danger text-center">
                        <button class="close" data-dismiss="alert">×</button>
                        <?php echo $errorMsg;?>
                    </div>
                </div>
            </div>
            <?php }
            else if(isset($errors) && !empty($errors)){?>
            <div class="row">
                <div class="col-xs-12">
                    <div class="alert alert-danger text-center">
                        <button class="close" data-dismiss="alert">×</button>
                        <strong><i class="fa fa-exclamation-circle"></i> </strong> Following errors occurred.
                        <?php if(isset($errors['message'])):?>
                        <ul><li style="font-size: .9em;"><?php echo $errors['message'];?></li></ul>
                        <?php endif;?>
                    </div>
                </div>
            </div>
            <?php }?>
