<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $pageTitle;?> | Residential Internet Service, AITSO, Dhaka Cantonment</title>
        <link rel="shortcut icon" href="<?php echo BASE_URL?>/img/aitso.jpg" type="image/png" />
		<meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="css/bootstrap.min.css" />
        <link rel="stylesheet" href="css/font-awesome.css" />
        <link rel="stylesheet" href="css/unicorn-login.css" />
    	<script src="js/respond.min.js"></script>
        <style>
        .marquee {
          overflow: hidden;
          font-weight: bold;
          font-size: +1.25em;
          padding: 6px;
          background-color: #EAEAEA;
          color:#022161;
        }
        </style>
	</head>    <body>
        <div id="container" style="background-color:   #FFF; 
            padding:            10px 10px;    
            -moz-box-shadow:    inset 0 0 3px #000000;
            -webkit-box-shadow: inset 0 0 2px #000000;
            box-shadow:         inset 0 0 1px #000000;">
            <div id="logo">
                <img src="img/aitso.jpg" alt="" />
                <div>
                    <div class="marquee">Welcome to AITSO Residential Internet. We are going to digitize!!!</div>
                </div>
            </div>
                
            <div id="loginbox" style="background-color:#F2F0F1;">
                <form id="loginform" action="login.php" method="post">
                    <p style="font-weight: bold; color: #3F3F3F;">Enter username and password to continue.</p>
                    <?php $errCls = isset($errors['message']) ? ' has-error' : '';?>
                    <?php $alertCls = isset($errors['message']) ? ' alert-danger' : '';?>
                    <div class="input-group input-sm<?php echo $errCls;?>">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span><input class="form-control" type="text" id="username" name="username" placeholder="Username" value="<?php echo $username;?>" />
                    </div>
                    <div class="input-group<?php echo $errCls;?>">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span><input class="form-control" type="password" id="password" name="password" placeholder="Password" value="" />
                    </div>
                    <div class="form-actions clearfix">
                        <div class="text-center<?php echo $alertCls;?>">
                            <?php if(isset($errors['message'])){
                                echo $errors['message'];
                            } else {
                                echo '&nbsp;';
                            }?>
                            
<!--                            <a href="#recoverform" class="flip-link to-recover">Lost password?</a>-->
                        </div>
                        <input type="submit" class="btn btn-block btn-success" value="Login" />
                    </div>
                </form>
                <form id="recoverform" action="login.php" method="post">
    				<p>Enter your username and mobile number below <br>and we will send you password.</p>
    				<div class="input-group input-sm">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span><input class="form-control" type="text" id="username" name="username" placeholder="Username" value="<?php echo $username;?>" />
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-mobile-phone" aria-hidden="true" style="font-size: +1.5em;"></i></span><input class="form-control" type="text" id="mobilephone" name="mobilephone" placeholder="Mobile number" value="" />
                    </div>
                    <div class="form-actions clearfix">
                        <div class="pull-left">
                            <a href="#loginform" class="flip-link to-login">Click to login</a>
                        </div>
                        <input type="submit" class="btn btn-block btn-inverse" value="Recover" />
                    </div>
                </form>
            </div>
        </div>
        
        <script src="js/jquery.min.js"></script>  
        <script src="js/jquery-ui.custom.min.js"></script>
        <script src="js/unicorn.login.js"></script> 
        <script src="js/jquery.marquee.min.js"></script>
        <script>
            $('.marquee').marquee();
        </script>
    </body>
</html>
