<!DOCTYPE html>
<html lang="en">
<head>
    <title>ArmyRIS | <?php echo $pageTitle;?> | Residential Internet Service, AITSO, Dhaka Cantonment</title>
    <link rel="shortcut icon" href="<?php echo BASE_URL?>/img/aitso.jpg" type="image/png" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="css/font-awesome.css" />
    <link rel="stylesheet" href="css/unicorn-login.css" />
    <link rel="stylesheet" href="css/lightbox.css" />
    <link rel="stylesheet" href="css/style.css" />
    <script src="js/respond.min.js"></script>
    <script src="js/jquery.min.js"></script>        
    <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet">
</head>    
<body style="">
    <div class="container" style="width:100%;">
        <div id="content">
            <div class="row header">
                <img class="img-responsive" src="img/Baner-Final.jpg" alt="AITSO" style="height: 90px;width: 100%;"/>
            </div>
            <div class="row">                
                <div class="col-sm-12 marquee-area">
                    <marquee style="overflow: hidden;font-weight: bold;font-size: +1.25em;color:#022161;" scrollamount="5">Welcome to AITSO Residential Internet. We Connect Your Home to The World !!!</marquee>
                </div>
            </div>            

            <div class="login-area row">
                <div class="container col-sm-10 col-sm-offset-1">
                    <div class="col-sm-4">
                        <div class="login-about">
                            <?php require BASE_DIRECTORY.'/views/layouts/msg.phtml';?> 
                        </div>                      

                        <div class="section-title">
                            <h2>Sign In Here</h2>                        
                        </div>
                        <div class="login-form">
                            <div class="col-sm-11">
                                <form id="loginform" action="login.php" method="post">
                                    <?php if(isset($errors['message'])):?>
                                        <div class="alert alert-danger">
                                            <?php echo $errors['message'];?>
                                        </div>
                                    <?php endif;?>
                                    <?php $errCls = isset($errors['message']) ? ' has-error' : '';?>
                                    <?php $alertCls = isset($errors['message']) ? ' alert-danger' : '';?>
                                    <div class="input-group input-sm<?php echo $errCls;?>">
                                        <span class="input-group-addon"><i class="fa fa-user"></i></span><input class="form-control" type="text" id="username" name="username" placeholder="Enter Username" value="<?php echo $username;?>" maxlength="30"/>
                                    </div>
                                    <div class="input-group input-sm<?php echo $errCls;?>">
                                        <span class="input-group-addon"><i class="fa fa-lock"></i></span><input class="form-control" type="password" id="password" name="password" placeholder="Enter Password" value="" maxlength="30" />
                                    </div>
                                    <div class="input-group input-sm form-actions clearfix pull-right">
                                        <input type="submit" class="form-control btn btn-success" value="Login" />
                                    </div>
                                </form>                              
                            </div>                      
                        </div>
                        
                        <div class="contact-address">
                            <h4>Contact Address</h4>
                            <address>                            
                                AITSO, Dhaka Cantonment<br>
                                Dhaka, Bangladesh<br>
                                @ 01769018585, Ext-8585<br>
                            </address>
                        </div>

                        <div class="usefull-link">
                            <h4>Useful Links</h4>
                            <?php require BASE_DIRECTORY.'/views/layouts/useful-links.phtml';?>
                        </div>
                    </div>
                    <!-- /col-md-4 -->
                    
                    
                    <div class="col-md-8">
                        <div class="row">
                            <div class="gellary-item">
                                <div class="stor-img">
                                    <a href="http://203.202.246.36/" target="_blank" ><img src="img/store.jpg" alt=""></a>
									<a class='cover-area' href="http://203.202.246.36" target="_blank">										
										<div class="enjoy-css">Click to visit IT Palace </div>
									</a>
                                </div>
                                <div class="gallary-img">
                                  <div class="left-img">
                                    <a href="img/dit1.jpg" data-lightbox="roadtrip">
                                        <img src="img/dit1.jpg">
                                    </a>
                                </div>
                                <div class="left-img">
                                    <a href="img/Leaflet.jpg" data-lightbox="roadtrip">
                                        <img src="img/Leaflet.jpg">
                                    </a>
                                </div>
                                <div class="left-img">
                                    <a href="img/dit2.jpg" data-lightbox="roadtrip">
                                        <img src="img/dit2.jpg">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-bottom row">
            <?php require BASE_DIRECTORY.'/views/layouts/admin-footer.phtml';?>
        </div>
    </div>
</div>
<style>
.banner-img img {
    max-width: 100%;
}
.banner-img {
    padding: 20px 0px;
}
.login-form {
    background-color: #a6dbec;
    display: inline-block;
    padding: 20px;
    border-radius: 2px;
}
.login-area  {
    background: #689268;
}
.login-about ul {
    padding: 0px 20px;
    text-align: justify;
}
.login-area h2 {
    color: #fff;
    font-size: 22px;
}
.stor-img img {
    max-width: 100%;
}
.gallary-img img {
    width: 100%;
    height: 100%;
}
.left-img {
    width: 33.33%;
    float: left;
    height: 225px;
}
.gellary-item {
    margin-right: -15px;
}
.list-inline>li {
    color: #fff;
    font-size: 16px;
}

.list-inline>li a {
    color: #fff;
    margin-left: 5px;
}
</style>

<script src="js/jquery.min.js"></script>  
<script src="js/jquery-ui.custom.min.js"></script>
<script src="js/unicorn.login.js"></script> 
<script src="js/jquery.marquee.min.js"></script>
<script src="js/coruosel.js"></script>
<script src="js/lightbox.js"></script>
<script src="js/bootstrap.min.js"></script>
<script>
    $('.marquee').marquee();
</script>
</body>
</html>
