                           
                    <div class="section-title" style="margin-right: 33%;">
                        <h2>Dear Valued Subscriber</h2>                        
                    </div>
                    <div class="about-details">
                         <div class="about-details-top">
                            <p>To recharge your account and activate internet please follow these steps:</p>
                            <ul>
                                <li>Login your account using your username and password.</li>
                                <li>Click "Recharge Account". Put your scratch card no and click "Recharge".</li>
                                <li>Click "Internet Check in". Then click on "Click here to Enable / Extend Internet Connection..."</li>
                            </ul>
                        </div>
                        <div class="about-details-footer">
                            <p>To avoid internet disconnection please recharge and activate internet in advance before your account is being suspended.</p>
                        </div>
                    </div>