
<ul class="list-inline">
    <li><a href="http://www.google.com/" title="Google" target="_blank"><i class="fa fa-google-plus"></i></a></li>
    <li><a href="http://www.yahoo.com/" title="Yahoo" target="_blank"><i class="fa fa-yahoo"></i></a></li>
	<li><a href="http://www.gmail.com/" title="Gmail" target="_blank"><i class="fa fa-envelope"></i></a></li>
    <li><a href="http://www.facebook.com/" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
    <li><a href="http://www.youtube.com/" title="Youtube" target="_blank"><i class="fa fa-youtube"></i></a></li>
	<li><i class="fa fa-facebook"></i><a href="http://www.dsebd.org/" title="Dhaka Stock Exchange" target="_blank">Dhaka Stock Exchange</a></li>
    <li><i class="fa fa-facebook"></i><a href="http://www.prothom-alo.com/" title="Prothom Alo" target="_blank">Prothom Alo</a></li>
	<li><i class="fa fa-facebook"></i><a href="http://bangla.bdnews24.com/" title="BD News24" target="_blank">BD News24</a></li>
    <li><i class="fa fa-facebook"></i><a href="http://www.kalerkantho.com/" title="Kaler Kontho" target="_blank">Kaler Kontho</a></li>
    <li><i class="fa fa-facebook"></i><a href="http://www.thedailystar.net/" title="The Daily Star" target="_blank">The Daily Star</a></li>
    <li><i class="fa fa-facebook"></i><a href="http://www.bbc.com/news" title="BBC" target="_blank">BBC</a></li>
    <li><i class="blink"></i><a href="http://203.202.246.36" title="" target="_blank">IT PALACE</a></li>
	  
</ul>


