<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Back to Scratch Card Lots">
                    <a href="lots.php" style="color: white;">Scratch Card Lots</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="lot-add.php">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="amount">Monetary Value of each card <span style='color:red;'>*</span></label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['amount'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="amount" id="amount" value="<?php echo $amount;?>" placeholder="Amount" autocomplete="off" />
                            <?php if(isset($errors['amount'])):?><span class="help-inline" for="amount"><?php echo $errors['amount'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="quantity">How many cards <span style='color:red;'>*</span></label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['quantity'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="quantity" id="quantity" value="<?php echo $quantity;?>" placeholder="Quantity" autocomplete="off" />
                            <?php if(isset($errors['quantity'])):?><span class="help-inline" for="quantity"><?php echo $errors['quantity'];?></span><?php endif;?>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="c_digits">Scratch Card Parameters</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['c_digits'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4">
                                    Digits <span style='color:red;'>*</span>
                                    <input type="text" class="form-control input-sm" name="c_digits" id="c_digits" value="<?php echo $c_digits;?>" placeholder="Firstname" autocomplete="off" />
                                    <?php if(isset($errors['c_digits'])):?><span class="help-inline" for="c_digits"><?php echo $errors['c_digits'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['c_prefix'])){echo ' has-error';}?>">
                                    <i>Prefix (optional)</i>
                                    <input type="text" class="form-control input-sm" name="c_prefix" id="c_prefix" value="<?php echo $c_prefix;?>" placeholder="Prefix" autocomplete="off" />
                                    <?php if(isset($errors['c_prefix'])):?><span class="help-inline" for="c_prefix"><?php echo $errors['c_prefix'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="s_digits">Serial Number Parameters</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['s_digits'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4">
                                    Digits <span style='color:red;'>*</span>
                                    <input type="text" class="form-control input-sm" name="s_digits" id="s_digits" value="<?php echo $s_digits;?>" placeholder="Firstname" autocomplete="off" />
                                    <?php if(isset($errors['s_digits'])):?><span class="help-inline" for="s_digits"><?php echo $errors['s_digits'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['s_prefix'])){echo ' has-error';}?>">
                                    Prefix <span style='color:red;'>*</span>
                                    <input type="text" class="form-control input-sm" name="s_prefix" id="s_prefix" value="<?php echo $s_prefix;?>" placeholder="Prefix" autocomplete="off" />
                                    <?php if(isset($errors['s_prefix'])):?><span class="help-inline" for="s_prefix"><?php echo $errors['s_prefix'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Generate" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
