<div class="row">
    <div class="col-xs-9">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="GO to Add Scratch Card">
                    <a href="lot-add.php" style="color: white;">Add Scratch Card</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <?php if(empty($data)):?>
                <p><h4 class="text-center">No payment record found!</h4></p>
                <?php else:?>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Amount (<?php echo CURRENCY;?>)</th>
                            <th>Quantity</th>
                            <th>Used</th>
                            <th>Available</th>
                            <th>Card Generated</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data as $d): ?>
                            <tr>
                                <td class="text-right"><?php echo Utility::thousandSeperator($d['amount']); ?></td>
                                <td class="text-right"><?php echo Utility::thousandSeperator($d['qty']); ?></td>
                                <td class="text-right"><?php echo Utility::thousandSeperator($d['used']); ?></td>
                                <td class="text-right"><?php echo Utility::thousandSeperator($d['available']); ?></td>
                                <td><?php echo Date::niceDateTime($d['created_at']); ?></td>
                                <td><a href="excel-export.php?id=<?php echo $d['id'];?>">Excel</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>