
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="List Corporate Subscribers">
                    <a href="list.php" style="color: white;">List</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="add-payment.php" name="subscriber_add_upd" id="subscriber_add_upd">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="subscriber">Corporate Subscriber</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['subscriber'])){echo ' has-error';}?>">
                            Subscriber Name and Mobile
                            <select name="subscriber" id="subscriber" class="form-control input-sm">
                                <option value="">-- SELECT SUBSCRIBER --</option>
                                <?php foreach($subscribers as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$subscriber){echo 'selected';}?>><?php echo $val;?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['subscriber'])):?><span class="help-inline" for="subscriber"><?php echo $errors['subscriber'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="amount"><?php echo trim($comment_prefix);?></label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['amount'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-3">
                                    Month
                                    <select name="month" id="month" class="form-control input-sm">
		                                <option value="">-- SELECT MONTH --</option>
		                                <?php foreach($months as $key=>$val):?>
		                                <option value="<?php echo $key;?>" <?php if($key==$month){echo 'selected';}?>><?php echo $val;?></option>
		                                <?php endforeach;?>
		                            </select>
                            		<?php if(isset($errors['month'])):?><span class="help-inline" for="month"><?php echo $errors['month'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3">
                                    Year
                                    <select name="year" id="year" class="form-control input-sm">
		                                <option value="">-- SELECT YEAR --</option>
		                                <?php foreach($years as $val):?>
		                                <option value="<?php echo $val;?>" <?php if($val==$year){echo 'selected';}?>><?php echo $val;?></option>
		                                <?php endforeach;?>
		                            </select>
                            		<?php if(isset($errors['year'])):?><span class="help-inline" for="year"><?php echo $errors['year'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="amount">Amount</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['amount'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-2">
                                	Amount in <?php  echo CURRENCY;?>
                                    <input type="text" class="form-control input-sm" name="amount" id="amount" value="<?php echo $amount;?>" placeholder="Official Mobile Number" autocomplete="off" style="text-align:right;" />
                                    <?php if(isset($errors['amount'])):?><span class="help-inline" for="amount"><?php echo $errors['amount'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Create" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
<script>
$(function() {    
    $('#subscriber').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/corporate-subscriber-price-by-sid.php',
            data : {id: $(this).val()},
            success : function (amt) {
                        $('#amount').val(amt);
                    }
        });
    });
});
</script>