<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>
                </span>
                <h5>Corporate Subscribers</h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add Corporate Subscribers">
                    <a href="add.php" style="color: white;">Add</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered table-striped table-hover" style="border-top:#229955 solid 1px;">
                    <thead>
                        <tr>
                            <th>SL</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Mobile</th>
                            <th>Package</th>
                            <th>Price (<?php echo CURRENCY;?>)</th>
                            <th>Status</th>
                            <th style="width:65px;">Action</th> 
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i=0;?>
                        <?php foreach ($data as $d): ?>
                            <tr>
                                <td class="text-right"><?php echo $limit*($page-1) + ++$i;?>.</td>
                                <td class=""><?php echo $d['firstname'];?></td>
                                <td class=""><?php echo $d['address'];?></td>
                                <td class=""><?php echo $d['official_mobile'];?></td>
                                <td class=""><?php echo $d['package'];?></td>
                                <td class="text-right"><?php echo Utility::commaSeperator($d['price']);?></td>
                                <td class="text-center"><?php echo isset($subscriber_statuses[$d['status_id']]) ? $subscriber_statuses[$d['status_id']]: ''; ?></td>
                                <td class="text-right">
                                    <a href="<?php echo BASE_URL.'/corporate-subscriber/details.php?id='.$d['id'];?>" title="View Details" class="text-success"><i class="fa fa-eye"></i></a> | 
                                    <a href="<?php echo BASE_URL.'/corporate-subscriber/edit.php?id='.$d['id'];?>" title="Edit Subscriber" class="text-primary"><i class="fa fa-edit"></i></a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <?php echo $paginationStr;?>
            </div>
        </div>
    </div>
</div>