
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5>Create New User</h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Back to Users List Page">
                    <a href="index.php" style="color: white;">Back to Users List</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="" name="user_inpt_frm" id="user_inpt_frm">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="username">Username</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['username'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="username" id="username" value="<?php echo $username;?>" placeholder="Username" autocomplete="off" />
                            <?php if(isset($errors['username'])):?><span class="help-inline" for="username"><?php echo $errors['username'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="password">Password</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['password'])){echo ' has-error';}?>">
                            <input type="password" class="form-control input-sm" name="password" id="password" value="<?php echo $password;?>" placeholder="Password" autocomplete="off" />
                            <?php if(isset($errors['password'])):?><span class="help-inline" for="password"><?php echo $errors['password'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="confirm_password">Confirm Password</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['confirm_password'])){echo ' has-error';}?>">
                            <input type="password" class="form-control input-sm" name="confirm_password" id="confirm_password" value="<?php echo $confirm_password;?>" placeholder="Confirm Password" autocomplete="off" />
                            <?php if(isset($errors['confirm_password'])):?><span class="help-inline" for="confirm_password"><?php echo $errors['confirm_password'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="ba_no">BA No</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['ba_no'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="ba_no" id="ba_no" value="<?php echo $ba_no;?>" placeholder="BA NO" autocomplete="off" />
                            <?php if(isset($errors['ba_no'])):?><span class="help-inline" for="ba_no"><?php echo $errors['ba_no'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="firstname">Full Name</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['firstname'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4">
                                    <input type="text" class="form-control input-sm" name="firstname" id="firstname" value="<?php echo $firstname;?>" placeholder="Firstname" autocomplete="off" />
                                    <?php if(isset($errors['firstname'])):?><span class="help-inline" for="firstname"><?php echo $errors['firstname'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['lastname'])){echo ' has-error';}?>">
                                    <input type="text" class="form-control input-sm" name="lastname" id="lastname" value="<?php echo $lastname;?>" placeholder="Lastname" autocomplete="off" />
                                    <?php if(isset($errors['lastname'])):?><span class="help-inline" for="lastname"><?php echo $errors['lastname'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="rank">Rank</label>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['rank'])){echo ' has-error';}?>">
                            <select name="rank" id="rank" class="form-control input-sm">
                                <option value="">--SELECT RANK--</option>
                                <?php foreach($ranks as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$rank){echo 'selected';}?>><?php echo $val;?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['rank'])):?><span class="help-inline" for="rank"><?php echo $errors['rank'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="mobile">Mobile</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['mobile'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="mobile" id="mobile" value="<?php echo $mobile;?>" autocomplete="off" />
                            <?php if(isset($errors['mobile'])):?><span class="help-inline" for="mobile"><?php echo $errors['mobile'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="email">Email</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['email'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="email" id="email" value="<?php echo $email;?>" autocomplete="off" />
                            <?php if(isset($errors['email'])):?><span class="help-inline" for="email"><?php echo $errors['email'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="is_support_asst">Support Assistant</label>
                        <div class="col-sm-9 col-md-9 col-lg-10">
                            <label class="fnt-nrml"><input type="checkbox" name="is_support_asst" value="1" <?php if($is_support_asst == '1'){echo 'checked';}?> /> Mark as Support Assistant</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label">Roles</label>
                        <?php if(isset($errors['roles'])){
                            $hasErrorClass = ' has-error';
                            $helpInlineClass = ' help-inline'; // color: #b94a48;
                        }else{
                            $hasErrorClass = '';
                            $helpInlineClass = '';
                        }?>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php echo $hasErrorClass;?>">
                            <?php foreach($roles as $key=>$val):?>
                            <label class="fnt-nrml<?php echo $helpInlineClass;?>"><input type="checkbox" name="roles[]" value="<?php echo $key;?>" <?php if(in_array($key, $uroles)){echo 'checked';}?> /> <?php echo $val;?></label>
                            <?php endforeach;?>
                            <?php if(isset($errors['roles'])):?><br><span class="help-inline"><?php echo $errors['roles'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Create" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
