<div class="row">
    <div class="col-xs-12">
        <span class="badge badge-purple"><b>Thank you for participating in survey.</b></span>
    </div>
</div>

<?php /*?>
<div class="row">
    <div class="col-xs-12">
        <h3><?php echo $info['name'];?></h3>
        <?php echo $info['desc'];?>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <?php foreach($questions as $id=>$val):?>
            <b>Ques: <?php echo $val['text'];?></b><br>
            <i>Type: <?php echo Survey::$question_types[$val['type']];?></i><br>
        <?php if(!empty($val['options'])):?>
        <b>Options:</b>
        <ul>
            <?php foreach($val['options'] as $option):?>
            <li><?php echo $option;?></li>
            <?php endforeach;?>
        </ul>
        <?php endif;?>
        <hr />
        <?php endforeach;?>
    </div>
</div>
<?php */?>
