<?php 
$tr_class = [
    0 => 'text-muted',
    //1 => 'text-success',
    1 => '',
    2 => 'text-danger',
];
?>
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-th-list"></i></span>
                <h5>Survey List</h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Go to Add New Survey page">
                    <a href="add.php" style="color: white;">Add New Survey</a>
                </span>
            </div>
            <div class="widget-content">
                <?php if(!empty($surveys)):?>
                    <table class="table table-bordered table-striped table-condensed table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Questions</th>
                                <th>Participants</th>
                                <th>Created</th>
                                <th>Action</th>                            
                            </tr>
                        </thead>
                        <tbody>
                            <?php $i=0;?>
                            <?php foreach($surveys as $s):?>
                            <tr class="<?php echo $tr_class[ ($s['is_active']%2) ];?>">
                                <td><?php echo ++$i;?>.</td>
                                <td><?php echo $s['name'];?></td>
                                <td><?php echo $s['desc'];?></td>
                                <td class="text-right">
                                    <a href="<?php echo BASE_URL.'/survey/questions.php?survey_id='.$s['id'];?>"><?php echo Survey::countQuestions($s['id']);?></a>
                                </td>
                                <td class="text-right">
                                    <a href="<?php echo BASE_URL.'/survey/participants.php?survey_id='.$s['id'];?>"><?php echo Survey::countParticipants($s['id']);?></a>
                                </td>
                                <td><?php echo Date::niceDateTime($s['dtt_create']);?></td>
                                <td class="text-right">
                                    <?php if($s['is_active']==1){
                                        $txt = 'Disable'; $action = 0;
                                    } else{
                                        $txt = 'Enable'; $action = 1;
                                    }?>
                                    <a href="<?php echo BASE_URL.'/survey/enable-disable.php?survey_id='.$s['id'].'&action='.$action;?>" ><?php echo $txt;?></a>
                                </td>
                            </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                <?php else:?>
                <p>No data found.</p>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>