<div class="row">
    <div class="col-xs-12">
        <div class="clearfix bbtm">
            <div class="col-sm-2 raf-lft">Participant Name</div>
            <div class="col-sm-8 raf-rgt"><?php echo trim($participant['firstname'].' '.$participant['lastname']);?></div>
        </div>
        <div class="clearfix bbtm">
            <div class="col-sm-2 raf-lft">Participant BA no</div>
            <div class="col-sm-8 raf-rgt"><?php echo $participant['ba_no'];?></div>
        </div>
        <div class="clearfix bbtm">
            <div class="col-sm-2 raf-lft">Participation Date</div>
            <div class="col-sm-8 raf-rgt"><?php echo Date::niceDateTime($participant['participated_at']);?></div>
        </div>
        <div class="clearfix bbtm">
            <div class="col-sm-2 raf-lft">Survey Title</div>
            <div class="col-sm-8 raf-rgt"><?php echo $survey_details['name'];?></div>
        </div>
        <div class="clearfix bbtm">
            <div class="col-sm-2 raf-lft">Survey Details</div>
            <div class="col-sm-8 raf-rgt"><?php echo $survey_details['desc'];?></div>
        </div>
        <hr>
<div class="row">
    <div class="col-xs-12" style="padding-bottom: 30px;">
        <?php foreach($questions as $id=>$val):?>
            <b class="instrc">Ques: <?php echo $val['text'];?></b><br>
        <?php if(!empty($val['options'])):?>
        <?php $tmp = explode(Survey::$answer_seperator, $answers[$id]);?>
        <ul>
            <?php foreach($val['options'] as $key=>$option):?>
            <li class="<?php echo in_array($key, $tmp) ? 'blk' : 'gray';?>"><?php echo $option;?></li>
            <?php endforeach;?>
        </ul>
        <?php else:?>
        <?php echo $answers[$id].'<br><br>';?>
        <?php endif;?>
        <!--<hr />-->
        <?php endforeach;?>
    </div>
</div>

    </div>
</div>