<div class="row">
    <div class="col-xs-12">
        <h3><?php echo $survey_details['name'];?></h3>
        <?php echo $survey_details['desc'];?>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-th-list"></i></span>
                <h5><?php echo $pageTitle;?></h5>
            </div>
            <div class="widget-content">
                <table class="table table-bordered table-striped table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>BA</th>
                            <th>Rank</th>
                            <th>Name</th>
                            <th>Participated at</th>
                            <th>Action</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i=0;?>
                        <?php foreach($participants as $s):?>
                        <tr class="">
                            <td><?php echo ++$i;?>.</td>
                            <td><?php echo $s['ba_no'];?></td>
                            <td><?php echo $s['rank'];?></td>
                            <td><b><?php echo trim($s['firstname']. ' '. $s['lastname']);?></b></td>
                            <td><?php echo Date::niceDateTime($s['participated_at']);?></td>
                            <td class="text-center">
                                <a href="<?php echo BASE_URL;?>/survey/participant-details.php?sid=<?php echo $survey_id;?>&pid=<?php echo $s['participant_id'];?>">Details</a>
                            </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>							
            </div>
        </div>
    </div>
</div>