<div class="row">
    <div class="col-xs-12">
        <h3><?php echo $info['name'];?></h3>
        <?php echo $info['desc'];?>
        <p>
        Total questions: <span class="badge badge-purple"><?php echo count($questions);?></span>
        <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add new survey question">
            <a href="add-question.php?survey_id=<?php echo $survey_id;?>" style="color: white;">Add question</a>
        </span>
        </p>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <?php foreach($questions as $id=>$val):?>
            <b>Ques: <?php echo $val['text'];?></b><br>
            <i>Type: <?php echo Survey::$question_types[$val['type']];?></i><br>
        <?php if(!empty($val['options'])):?>
        <b>Options:</b>
        <ul>
            <?php foreach($val['options'] as $option):?>
            <li><?php echo $option;?></li>
            <?php endforeach;?>
        </ul>
        <?php endif;?>
        <hr />
        <?php endforeach;?>
    </div>
</div>
<?php //Utility::pa($questions);?>