
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5>Change Password</h5>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="" name="user_inpt_frm" id="user_inpt_frm">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="current_password">Current Password</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['current_password'])){echo ' has-error';}?>">
                            <input type="password" class="form-control input-sm" name="current_password" id="current_password" value="<?php echo $current_password;?>" placeholder="Current Password" autocomplete="off" />
                            <?php if(isset($errors['current_password'])):?><span class="help-inline" for="current_password"><?php echo $errors['current_password'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="new_password">New Password</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['new_password'])){echo ' has-error';}?>">
                            <input type="password" class="form-control input-sm" name="new_password" id="new_password" value="<?php echo $new_password;?>" placeholder="New Password" autocomplete="off" />
                            <?php if(isset($errors['new_password'])):?><span class="help-inline" for="new_password"><?php echo $errors['new_password'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="confirm_password">Confirm Password</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['confirm_password'])){echo ' has-error';}?>">
                            <input type="password" class="form-control input-sm" name="confirm_password" id="confirm_password" value="<?php echo $confirm_password;?>" placeholder="Confirm Password" autocomplete="off" />
                            <?php if(isset($errors['confirm_password'])):?><span class="help-inline" for="confirm_password"><?php echo $errors['confirm_password'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
