<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>
                </span>
                <h5><?php echo $pageTitle;?></h5>
            </div>
            <div class="widget-content nopadding">
                <?php if(empty($data)):?>
                <p><h4 class="text-center">No connectivity record found!</h4></p>
                <?php else:?>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Action</th>
                            <th>Date</th>
                            <th>Package</th>
                            <th>Connect from</th>
                            <th>Connect up to</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data as $d): ?>
                            <tr>
                                <td class="b"><?php echo $d['comment']; ?></td>
                                <td><?php echo Date::niceDateTime($d['created_at']); ?></td>
                                <td><?php echo $d['package_name']; ?></td>
                                <td><?php echo Date::niceDateTime($d['connection_from']); ?></td>
                                <td><?php echo Date::niceDateTime($d['connection_to']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>