<?php /*?>
MARQUE: 
http://aamirafridi.com/jquery/jquery-marquee-plugin
<?php */?>
<style>
.marquee {
  overflow: hidden;
  font-weight: bold;
}
</style>
<div class="row">
    <div class="col-xs-12">
        <?php /*?>
        <div class="alert alert-info">
            Welcome to <strong>Residential Internet Service</strong> home page.
            <a href="#" data-dismiss="alert" class="close">×</a>
        </div>
        <?php */?>
        <div class="widget-box">
            <div class="widget-content">
                <div class="row">
                    <div class="col-xs-12 col-sm-4">
                        <ul class="site-stats">
                            <li><div class="cc"><i class="fa fa-arrow-right"></i> <strong><?php echo Subscriber::getStatus($params['status_id']);?></strong> <br><small>My account status</small></div></li>
                            <?php if(Session::get('category')!='Free'):?>
                            <li><div class="cc"><i class="fa fa-arrow-right"></i> <strong><?php echo Date::niceDateTime($params['disconnect_date']);?></strong> <br><small>Disconnect date</small></div></li>
                            <!--<li class="divider"></li>-->
                            <li><div class="cc"><i class="fa fa-arrow-right"></i> <strong><?php echo Utility::thousandSeperator($params['payment_balance']) .' '.CURRENCY;?></strong> <br><small>Current balance</small></div></li>
                            <?php endif;?>
                            <li><div class="cc"><i class="fa fa-arrow-right"></i> <strong><?php echo $params['package_name'];?></strong> <br><small>Package</small></div></li>
							<?php if($params['category'] == 'Complementary'):?>
							<li><div class="cc"><i class="fa fa-arrow-right"></i> <strong><?php echo Utility::commaSeperator($params['complementary_amount']), ' ', CURRENCY;?></strong> <br><small>Complementary Amount</small></div></li>
							<?php endif;?>
                        </ul>
                    </div>
                    <div class="col-xs-12 col-sm-8">
                        <div class="alert alert-info alert-block">
                            <div class="marquee">Welcome to AITSO Residential Internet. We are going to digitize!!!</div>
                        </div>
                        <div class="alert alert-danger alert-block">
                            <?php if(!empty($days_remaining_str)):?>
                            <h4 class="alert-heading" style="color:#E74C3C !important;">Attention!</h4>
                            <?php echo $days_remaining_str;?>
                            <?php endif;?>
                        </div>
                        <?php if(!empty($surveys)):?>
                        <div class="alert alert-info alert-block">
                            <b>SURVEYS:</b>
<!--                            <ul class="list-unstyled">-->
                            <ul>
                                <?php foreach($surveys as $key=>$val):?>
                                <li><a href="survey/attend.php?id=<?php echo $key;?>" title="<?php echo $val;?>"><?php echo $val;?></a></li>
                                <?php endforeach;?>
                            </ul>
                        </div>
                        <?php endif;?>
                        <div class="alert alert-success alert-block">
                            Dear valued subscriber,<br>
                            
                            &#10173; When you will change/update your internet package,please inform our Residential Internet Call Center before recharge or change your package.</br>
                            &#10173;  When you recharge your account it will be activated and enabled at the right away.
                        </div>
                        <div class="alert alert-warning alert-block">
                            To avoid internet disconnection please recharge and activate internet in advance before your account is being suspended. If suspended please call 8585.
                        </div>
                        <div class="row col-sm-12 text-center">
                            <a href="<?php echo BASE_URL;?>/recharge-account.php"><h2><span class="badge badge-danger" style="font-size: 85%; background:#107C10;">Recharge Account</span></h2></a></div>
                            <?php /*?><div class="col-sm-5 text-left"><h2><span class="badge badge-danger" style="font-size: 85%;">Usage Graph</span></h2></div><?php */?>
                    </div>
                                        
                    
                    <hr>
                    <?php $graph_url = $graph_baseurl_by_router_no[Session::get('router_no')]."%3Cpppoe-".Session::get('username')."%3E/";?>
                    <object data="<?php echo $graph_url;?>" width="100%" height="500">
                        <embed src="<?php echo $graph_url;?>" width="100%" height="500"> </embed>
                        Error: Embedded data could not be displayed.
                    </object>
                </div>							
            </div>
        </div>					
    </div>
</div>

<script>
$('.marquee').marquee();
</script>