<style>
.widget-title{
	background: #d0d6c7 !important;
}
.widget-title h5{
	text-shadow: none !important;
	color: #565656 !important;
}
.widget-content table td{ font-size:.9em;}
.taskStatus span, .taskStatus span a{color: #d9534f !important; display:block;}
.taskDesc a{color: #333 !important; display:block;}
</style>


<div class="row">
	<div class="col-xs-12 col-sm-3">
	<div class="widget-box">
			<div class="widget-title">
				<h5>Subscribers by Status</h5>
			</div>
			<div class="widget-content nopadding">
				<table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/subscriber/index.php?sts=1';?>">Active</a></td>
                            <td class="taskStatus "><a href="<?php echo BASE_URL.'/subscriber/index.php?sts=1';?>"><span class="pending pull-right"><?php echo Utility::commaSeperator($SubscribersByStatus['active']);?></span></a></td>
                        </tr>
                        <tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/subscriber/index.php?sts=0';?>">Suspended</a></td>
                            <td class="taskStatus"><a href="<?php echo BASE_URL.'/subscriber/index.php?sts=0';?>"><span class="pending pull-right"><?php echo Utility::commaSeperator($SubscribersByStatus['suspended']);?></span></a></td>
                        </tr>
                        <tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/subscriber/index.php';?>">Total</a></td>
                            <td class="taskStatus"><a href="<?php echo BASE_URL.'/subscriber/index.php';?>"><span class="pending pull-right"><?php echo Utility::commaSeperator($SubscribersByStatus['total']);?></span></a></td>
                        </tr>
                    </tbody>
                </table>
			</div>
		</div>
		<div class="widget-box">
			<div class="widget-title">
				<h5>Complaints by Status</h5>
			</div>
			<div class="widget-content nopadding">
				<table class="table table-striped table-bordered">
                    <tbody>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=1';?>">Informed</a></td>
                            <td class="taskStatus"><span class="pending pull-right">
							<a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=1';?>"><?php echo Utility::commaSeperator($ComplaintByStatuses['informed']);?></a></span></td>
                        </tr>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=2';?>">In Progress</a></td>
                            <td class="taskStatus"><span class="pending pull-right"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=2';?>"><?php echo Utility::commaSeperator($ComplaintByStatuses['in_progress']);?></a></span></td>
                        </tr>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=3';?>">On Hold</a></td>
                            <td class="taskStatus"><span class="pending pull-right"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=3';?>"><?php echo Utility::commaSeperator($ComplaintByStatuses['on_hold']);?></a></span></td>
                        </tr>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=4';?>">Pending</a></td>
                            <td class="taskStatus"><span class="pending pull-right"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=4';?>"><?php echo Utility::commaSeperator($ComplaintByStatuses['pending']);?></a></span></td>
                        </tr>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=5';?>">Completed</a></td>
                            <td class="taskStatus"><span class="pending pull-right"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=5';?>"><?php echo Utility::commaSeperator($ComplaintByStatuses['completed']);?></a></span></td>
                        </tr>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=6';?>">Cancled</a></td>
                            <td class="taskStatus"><span class="pending pull-right"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&status=6';?>"><?php echo Utility::commaSeperator($ComplaintByStatuses['cancled']);?></a></span></td>
                        </tr>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict';?>">Total</a></td>
                            <td class="taskStatus"><span class="pending pull-right"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict';?>"><?php echo Utility::commaSeperator($ComplaintByStatuses['total']);?></a></span></td>
                        </tr>
                    </tbody>
                </table>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-3">
		<div class="widget-box">
			<div class="widget-title">
				<h5>Top Complainant</h5>
			</div>
			<div class="widget-content nopadding">
				<table class="table table-striped table-bordered">
                    <tbody>
                    <?php foreach($topComplainants as $tc):?>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&search='.$tc['ba_no'].'&rank='.$tc['rank_id'];?>"><?php echo trim($tc['rank'].' '.$tc['firstname'].' '.$tc['lastname']);?></a></td>
                            <td class="taskStatus"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&search='.$tc['ba_no'].'&rank='.$tc['rank_id'];?>"><span class="pending pull-right"><?php echo Utility::commaSeperator($tc['total']);?></span></a></td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
			</div>
		</div>
	</div>

	
	<div class="col-xs-12 col-sm-5">
		<div class="widget-box">
			<div class="widget-title">
				<h5>Complaints by Types</h5>
			</div>
			<div class="widget-content nopadding">
				<table class="table table-striped table-bordered">
                    <tbody>
                    <?php foreach($ComplaintByTypes as $sp):?>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&problem_type='.$sp['pb_type'];?>"><?php echo $sp['problem'];?></a></td>
                            <td class="taskStatus"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict&problem_type='.$sp['pb_type'];?>"><span class="pending pull-right"><?php echo Utility::commaSeperator($sp['total']);?></span></a></td>
                        </tr>
                    <?php endforeach;?>
                    	<tr>
                            <td class="taskDesc"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict';?>">Total</a></td>
                            <td class="taskStatus"><a href="<?php echo BASE_URL.'/complaint/general-report.php?dt_md=strict';?>"><span class="pending pull-right"><?php echo Utility::commaSeperator($ComplaintByTypesTotal);?></span></a></td>
                        </tr>
                    </tbody>
                </table>
			</div>
		</div>
	</div>
</div>