				<div class="row">
					<div class="col-xs-12">
						<div class="widget-box">
							<div class="widget-title">
								<span class="icon">
									<i class="fa fa-th-list"></i>
								</span>
								<h5>Dashboard</h5>
							</div>
							<div class="widget-content">
                                <?php
                                //Utility::pr($_SESSION);
                                //$my_roles = $roles->listUserPagesByRoles(Session::get('uid'));
                                //Utility::pr($my_roles);
                                ?>
							</div>
						</div>
                        
					</div>
                    
				</div>





