<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
            </div>
            <div class="widget-content">
                <form class="form-horizontal" method="post" action="internet-checkin.php" name="user_inpt_frm" id="user_inpt_frm">
                    <div class="clearfix bbtm">
                        <div class="col-sm-2 raf-lft">Current Status</div>
                        <div class="col-sm-9 raf-rgt"><?php echo Subscriber::getStatus($params['status_id']);?></div>
                    </div>
                    <?php if($params['status_id']==1):?>
                    <div class="clearfix bbtm">
                        <div class="col-sm-2 raf-lft">Disconnect date</div>
                        <div class="col-sm-9 raf-rgt"><?php echo Date::niceDateTime($params['disconnect_date']);?></div>
                    </div>
                    <?php endif;?>
                    <div class="clearfix bbtm">
                        <div class="col-sm-2 raf-lft">Category</div>
                        <div class="col-sm-9 raf-rgt"><?php 
                        echo $params['category'];
                        if($params['category'] == 'Complementary'){
                            echo ' (' .$params['complementary_amount']. ' '.CURRENCY.')';
                        }
                        ?></div>
                     </div>
                    <div class="clearfix bbtm">
                        <div class="col-sm-2 raf-lft">Current Balance</div>
                        <div class="col-sm-9 raf-rgt"><?php echo Utility::thousandSeperator($params['payment_balance']) .' '.CURRENCY;?></div>
                     </div>
                   
                    <div class="clearfix bbtm">
                        <div class="col-sm-2 raf-lft">Current Package</div>
                        <div class="col-sm-9 raf-rgt"><?php echo $params['package_name'];?></div>
                    </div>
                    <div class="clearfix bbtm">
                        <div class="col-sm-2 raf-lft">Package Price</div>
                        <div class="col-sm-9 raf-rgt"><?php echo $params['package_price'].' '.CURRENCY;?></div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <?php echo $btnTxt;?>
                    </div>
                    <?php 
                    //Utility::pr($params);
                    //echo 'username: '. $username;
                    ?>
                </form>
                
            </div>
        </div>			
    </div>
</div>
