<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-align-justify"></i></span>
                <h5><?php echo $pageTitle;?></h5>
            </div>
            <div class="widget-content">
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Username</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $username;?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">BA No</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $ba_no;?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Full Name</div>
                   <div class="col-sm-9 raf-rgt"><?php echo trim($firstname.' '.$lastname);?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Rank</div>
                   <div class="col-sm-9 raf-rgt"><?php echo isset($ranks[$rank]) ? $ranks[$rank] : '';?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Mobile</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $mobile;?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Email</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $email;?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Roles</div>
                   <div class="col-sm-9 raf-rgt"><?php 
                            $user_roles = '';
                            foreach($roles as $key=>$val){
                                if(in_array($key, $uroles)){
                                    $user_roles .= $val .', ';
                                }
                            }
                            echo rtrim($user_roles, ', ');
                            ?></div>
                </div>
            </div>
        </div>
    </div>
</div>
    
    
