
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5>Recharge Account</h5>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="recharge-account.php" name="user_inpt_frm" id="user_inpt_frm">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="">Current Balance</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['card_no'])){echo ' has-error';}?>">
                            <?php echo $recharge_params['payment_balance'].' '.CURRENCY;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="card_no">Scratch Card No</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['card_no'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="card_no" id="card_no" value="<?php echo $card_no;?>" placeholder="Enter Scratch Card No" autocomplete="off" />
                            <?php if(isset($errors['card_no'])):?><span class="help-inline" for="card_no"><?php echo $errors['card_no'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Recharge" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
