<style>
    #srch-rslt-mdl .modal-dialog  {width:75%;}
</style>
<form action="add.php" method="post">
<div class="row" style="margin-top:-10px; margin-bottom: 0;">
    <div class="col-xs-12">
        <div class="widget-box" style="margin-bottom:-10px;">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-users"></i></span>
                <h5>Search</h5>
            </div>
            <div class="widget-content nopadding">
                <div class="row" style="font-size:.8em; margin-bottom: 20px;">
                    <div class="col-md-3">
                        Username / BA / Name / Mobile:
                        <input type="text" class="form-control input-sm" name="str" id="str" value="<?php echo $str;?>" placeholder="" autocomplete="off" />
                    </div>
                    <div class="col-md-2">
                        Rank:
                        <select name="rank" id="rank" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($ranks as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$rank){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        Area:
                        <select name="area" id="area" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($areas as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$area){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        Building:
                        <select name="building" id="building" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($buildings as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$building){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <br>
                        <?php /*?><a href="#" id="open-modal" class="btn btn-success btn-sm"><span class="icon"><i class="fa fa-search"></i> </span> Search</a><?php */?>
                        <a href="#" class="btn btn-success btn-sm" data-toggle="modal" data-target="#srch-rslt-mdl"><span class="icon"><i class="fa fa-search"></i> </span> Search</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row" style="font-size:.8em; margin-top: 0px;">
    
    <div class="col-xs-6">
        <div class="widget-box" style="margin-right:-5px;">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-user"></i></span>
                <h5>Subscriber Information</h5>
            </div>
            <div class="widget-content subs-inf">
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Username</div>
                   <div class="col-sm-8 raf-rgt" id="tx_username">
                       <?php echo $data['username'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">BA No</div>
                   <div class="col-sm-8 raf-rgt" id="tx_ba">
                       <?php echo $data['ba_no'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Rank</div>
                   <div class="col-sm-8 raf-rgt" id="tx_rank">
                       <?php echo $data['rank'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Name</div>
                   <div class="col-sm-8 raf-rgt" id="tx_name">
                       <?php echo trim($data['firstname'].' '.$data['lastname']);?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">House</div>
                   <div class="col-sm-8 raf-rgt" id="tx_house">
                       <?php echo $data['house'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Building</div>
                   <div class="col-sm-8 raf-rgt" id="tx_buildig">
                       <?php echo $data['building'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Area</div>
                   <div class="col-sm-8 raf-rgt" id="tx_area">
                       <?php echo $data['area'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Mobile</div>
                   <div class="col-sm-8 raf-rgt" id="tx_mobile">
                       <?php echo $data['official_mobile'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Status</div>
                   <div class="col-sm-8 raf-rgt" id="tx_status">
                       <?php echo $data['status'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Connectivity up to</div>
                   <div class="col-sm-8 raf-rgt" id="tx_connectivity">
                       <?php echo $data['connection_to'];?>
                       <?php if(isset($errors['_id'])):?><span class="help-inline" for="str" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['_id'];?></span><?php endif;?>
                   </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xs-6">
        <div class="widget-box" style="margin-left:-5px;">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-align-justify"></i></span>
                <h5>Complaint Details</h5>
            </div>
            <div class="widget-content complain">
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Problem Since</div>
                   <div class="col-sm-8 raf-rgt">
                       <?php echo createDateTimeDropdown('pb_since', 'pb_since', '', $pb_since['d'],$pb_since['m'],$pb_since['y'],$pb_since['h'],$pb_since['i'],$pb_since['a'], true);?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Problem Type</div>
                   <div class="col-sm-8 raf-rgt">
                        <select id="ptype" name="ptype" style="width:350px; <?php if(isset($errors['ptype'])){echo 'border:#A94442 solid 1px; color:red;';}?>">
                            <option value="">--Select Type--</option>
                            <?php foreach($problemTypes as $key=>$val):?>
                            <option value="<?php echo $key;?>"<?php if($key==$ptype) echo ' selected';?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                       <?php if(isset($errors['ptype'])):?><span class="help-inline" for="ptype" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['ptype'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Problem Details</div>
                   <div class="col-sm-8 raf-rgt">
                       <textarea name="pdetails" rows="4" cols="65" placeholder="Describe in brief."><?php echo $pdetails;?></textarea>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Problem Status</div>
                   <div class="col-sm-8 raf-rgt">
                       <select id="new_status" name="status">
                            <option value="">--Select Status--</option>
                            <?php foreach(Complaint::$complaintAdminStatuses as $key=>$val){?>
                                <option value="<?php echo $key;?>"<?php if($key==$status) echo ' selected';?>><?php echo $val;?></option>
                            <?php }?>
                        </select>
                   </div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-3 raf-lft">Support-in-Charge</div>
                   <?php //Utility::pa($supports_in_charge); exit;?>
                   <div class="col-sm-8 raf-rgt">
                       <select id="support_in_charge" name="support_in_charge" style="width:350px; <?php if(isset($errors['support_in_charge'])){echo 'border:#A94442 solid 1px; color:red;';}?>">
                            <option value="">Select Support-in-Charge</option>
                            <?php foreach($supports_in_charge as $key=>$val){?>
                                <option value="<?php echo $key;?>"<?php if($key==$support_in_charge) echo ' selected';?>><?php echo $val['name'].' ('.$val['mobile'].')';?></option>
                            <?php }?>
                        </select>
                       <?php if(isset($errors['support_in_charge'])):?><span class="help-inline" for="support_in_charge" style="color:#A94442; background:#F2DEDE;"><?php echo $errors['support_in_charge'];?></span><?php endif;?>
                   </div>
                </div>
                <div class="clearfix bbtm">
                    <div class="col-sm-3 raf-lft"></div>
                    <div class="col-sm-8 raf-rgt">
                        <button class="btn btn-success btn-sm">Submit</button>
                        <input style="width:70px;" type="hidden" id="_id" name="_id" value="<?php echo $id;?>" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</form>
<?php // if(isset($errors)){
//     Utility::pr($errors);
//}
?>

<!-- Modal -->
<div class="modal fade" id="srch-rslt-mdl" tabindex="-1" role="dialog" aria-labelledby="srch-rslt-mdlLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="srch-rslt-mdlLabel">Search Result</h4>
      </div>
      <div class="modal-body" id="modal-body">
        ...
      </div>
    </div>
  </div>
</div>



    
<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area.php',
            data : {id: $(this).val()},
            success : function (msg) {
                        $('#building').html(msg);
                    }
        });
    });    
    
    $('#srch-rslt-mdl').on('shown.bs.modal', function () {
         searchSubscribers($('#str').val(), $('#rank').val(), $('#area').val(), $('#building').val()); 
    });
    
});

function searchSubscribers(str, rank, area, building)
{
    $.ajax({
        type : 'POST',
        url  : "<?php echo BASE_URL;?>/modules/ajx/search-subscribers-by-keys.php",
        data : {str : str, rank: rank, area:area, building:building},
        success : function (msg) {
            $('#modal-body').html(msg);
        }
    });
}
</script>