<form class="form-horizontal" method="post" action="" name="user_inpt_frm" id="user_inpt_frm">
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-align-justify"></i></span>
                <h5> SUBSCRIBER DETAILS</h5>
            </div>
            <div class="widget-content">
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Username</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $result['username'];?></div>
                   <div class="col-sm-2 raf-lft">Name</div>
                   <div class="col-sm-2 raf-rgt"><?php echo trim($result['firstname'].' '.$result['lastname']);?></div>
                   <div class="col-sm-2 raf-lft">Rank</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $result['rank'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Mobile</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $result['official_mobile'];?></div>
                   <div class="col-sm-2 raf-lft">Address</div>
                   <div class="col-sm-6 raf-rgt"><?php echo $result['house_no'].', '.$result['building'].', '.$result['area'];?></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-align-justify"></i></span>
                <h5> PROBLEM DETAILS</h5>
            </div>
            <div class="widget-content">
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Problem since</div>
                   <div class="col-sm-2 raf-rgt"><?php echo Date::niceDateTime2($result['pb_since']);?></div>
                   <div class="col-sm-2 raf-lft">Informed</div>
                   <div class="col-sm-2 raf-rgt"><?php echo Date::niceDateTime2($result['dtt_add']);?></div>
                   <?php if(!empty($result['dtt_mod'])):?>
                   <div class="col-sm-2 raf-lft">Last updated</div>
                   <div class="col-sm-2 raf-rgt"><?php echo Date::niceDateTime2($result['dtt_mod']);?></div>
                   <?php endif;?>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="pb_type">Problem Type</label>
                    <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['pb_type'])){echo ' has-error';}?>">
                        <select name="pb_type" id="pb_type" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($problem_types as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$pb_type){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                        <?php if(isset($errors['pb_type'])):?><span class="help-inline" for="pb_type"><?php echo $errors['pb_type'];?></span><?php endif;?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="pb_details">Problem Details</label>
                    <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['pb_details'])){echo ' has-error';}?>">
                        <textarea rows="2" class="form-control" name="pb_details"><?php echo $pb_details;?></textarea>
                        <?php if(isset($errors['pb_details'])):?><span class="help-inline" for="pb_details"><?php echo $errors['pb_details'];?></span><?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-align-justify"></i></span>
                <h5> SUPPORT DETAILS</h5>
            </div>
            <div class="widget-content">
                <div class="form-group">
                    <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="pb_type">Status</label>
                    <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['status'])){echo ' has-error';}?>">
                        <select id="new_status" name="status">
                            <option value="">--Select Status--</option>
                            <?php foreach(Complaint::$complaintAdminStatuses as $key=>$val){?>
                                <option value="<?php echo $key;?>"<?php if($key==$status) echo ' selected';?>><?php echo $val;?></option>
                            <?php }?>
                        </select>
                        <?php if(isset($errors['status'])):?><span class="help-inline" for="status"><?php echo $errors['status'];?></span><?php endif;?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="pb_type">Support Type</label>
                    <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['pb_type'])){echo ' has-error';}?>">
                        <select name="support_type" id="support_type" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($support_types as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$support_type){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                        <?php if(isset($errors['support_type'])):?><span class="help-inline" for="support_type"><?php echo $errors['support_type'];?></span><?php endif;?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="support_details">Support Details</label>
                    <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['support_details'])){echo ' has-error';}?>">
                        <textarea rows="2" class="form-control" name="support_details"><?php echo $support_details;?></textarea>
                        <?php if(isset($errors['support_details'])):?><span class="help-inline" for="support_details"><?php echo $errors['support_details'];?></span><?php endif;?>
                    </div>
                </div>
                <div class="form-actions">
                    <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                    <input type="submit" value="Update" class="btn btn-primary">
                </div>
            </div>
        </div>
    </div>
</div>
</form>