<style>
    table a{color:#000;}
</style>
<div class="col-xs2">
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon">
                <i class="fa fa-th-list"></i>
            </span>
            <h5>Search</h5>
            <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add New Complaint">
                <a href="add.php" style="color: white;">Add Complaint</a>
            </span>
        </div>
        <div class="widget-content" style="font-size: .9em; overflow: hidden;">
            
            
            
<form method="get" action="">
        <div class="col-md2" style="font-size: .9em;">
            <label for="search">
                <span>UserName/FullName/BaNumber/Phone:</span><br>
                <input type="text" name="search" id="search" value="<?php echo $search_txt;?>" style="width: 250px; border: solid 1px #7A7A7A; color:#000;" />
            </label>

            <label for="area">
                <span>Area:</span><br>
                <select id="area" name="area">
                    <option value=""><label>--Select Area--</label></option>
                    <?php
                    foreach($areas as $key=>$val) {
                        ?><option value="<?php echo $key;?>"<?php if($area == $key){echo ' selected';}?>><?php echo $val;?></option><?php
                    }		
                    ?>
                </select>
            </label>

            <label for="building">
                <span>Building:</span><br>
                <select id="building" name="building">
                    <option value=""><label>--Select Building--</label></option>
                    <?php
                    foreach($buildings as $key=>$val) {
                        ?><option value="<?php echo $key;?>"<?php if($building == $key){echo ' selected';}?>><?php echo $val;?></option><?php
                    }       
                    ?>
                </select>
            </label>

        <label for="status">
            <span>Status:</span><br>
            <select id="status" name="status">
                <option value="">--Select Status--</option>
                <?php foreach(Complaint::$complaintAdminStatuses as $key=>$val):?>
                <option value="<?php echo $key;?>"<?php if($key==$status) echo ' selected';?>><?php echo $val;?></option>
                <?php endforeach;?>
            </select>
        </label>
        <label>&nbsp;</label>
        <label>&nbsp;</label>
        <label>&nbsp;</label>
        <label>&nbsp;</label>
        <label for="rank">
            <span>Rank:</span><br>
            <select id="rank" name="rank">
                <option value="">--Select Rank--</option>
                <?php
                foreach($ranks as $key=>$val) {
                    ?><option value="<?php echo $key;?>" <?php if($rank == $key) echo 'selected';?>><?php echo $val;?></option><?php
                }?>
            </select>
        </label>
        <label class="checkbox-inline">
            <br>
            <input type="checkbox"  id="rank_opt" name="rank_opt"<?php if($rank_opt=='1'){echo ' checked';}?> value="1">And above
        </label>
        </div>

        <div class="col-md2" style="font-size: .9em;">
            <label for="date_from">
                <span>Date from</span><br>
                <input  type="text" class="datepicker" id="date_from" name="date_from" value="<?php echo $date_from;?>" style="border: solid 1px #7A7A7A; color:#000;" />
            </label>
            <label for="date_to">
                <span>Date to</span><br>
                <input  type="text" class="datepicker" id="date_to" name="date_to" value="<?php echo $date_to;?>" style="border: solid 1px #7A7A7A; color:#000;" />
            </label>
            <label for="problem_type">
                <span>Complain:</span><br>
                <select id="problem_type" name="problem_type">
                    <option value="">--Select Complain--</option>
                    <?php
                    foreach($problem_types as $key=>$val) {
                        ?><option value="<?php echo $key;?>" <?php if($problem_type == $key) echo 'selected';?>><?php echo $val;?></option><?php
                    }?>
                </select>
            </label>
            &nbsp;
            <label for="frequency">
                <span>Frequency:</span><br>
                <input type="text" name="frequency" id="frequency" value="<?php echo $frequency;?>" style="width: 35px; border: solid 1px #7A7A7A; color:#000;" />
                <input type="checkbox"  id="frequency_opt" name="frequency_opt"<?php if($frequency_opt=='1'){echo ' checked';}?> value="1">And above
            </label>
            &nbsp;
            <label style="margin-left:20px;">
                <br>
                <button type="submit" name="search" class="btn-sm"><span class="glyphicon glyphicon-search"></span> Search</button>
            </label>
        </div>
</form>
          
<?php // Utility::pa($data);?>
        <table class="table table-bordered table-striped table-hover data-table">
            <thead>
                <tr style="border-top:1px solid #D9D9D9;">
                    <th>SL</th>
                    <th>Username</th>
                    <th>Rank</th>
                    <th>Fullname</th>
                    <th>Address (House, Building, Area</th>
                    <th>Total Complains</th>
                </tr>
            </thead>
            <tbody style="font-size:1em;">
                <?php $i=0;?>
                <?php foreach($data as $d):?>
                <?php $url = "general-report.php?search={$d['username']}&date_from={$date_from}&date_to={$date_to}&status={$status}&problem_type={$problem_type}&page=1";?>
                <tr>
                    <td class="text-right"><a href="<?php echo $url;?>"><?php echo ++$i;?>.</a></td>
                    <td><a href="<?php echo $url;?>"><?php echo $d['username'];?></a></td>
                    <td><a href="<?php echo $url;?>"><?php echo $d['rank'];?></a></td>
                    <td><a href="<?php echo $url;?>"><?php echo trim($d['firstname'].' '.$d['lastname']);?></a></td>
                    <td><a href="<?php echo $url;?>"><?php echo $d['address'];?></a></td>
                    <td class="text-right"><a href="<?php echo $url;?>"><?php echo $d['total_complains'];?></a></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
            
        </div>
    </div>
</div>

<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area.php',
            data : {id: $(this).val()},
            success : function (msg) {
                $('#building').html(msg);
            }
        });
    });
});
</script>