<style>
    table a{color:#000;}
</style>
<div class="col-xs2">
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon">
                <i class="fa fa-th-list"></i>
            </span>
            <h5>Search</h5>
            <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add New Complaint">
                <a href="add.php" style="color: white;">Add Complaint</a>
            </span>
        </div>
        <div class="widget-content" style="font-size: .9em; overflow: hidden;">
            
            
            
<form method="post" action="">    
    <!--<div class="row col-md0 col-md-offset srch" style="font-size: .9em;">-->
        <div class="col-md2" style="font-size: .9em;">
            <label for="search">
                <span>UserName/FullName/BaNumber/Phone:</span><br>
                <input type="text" name="search" id="search" value="<?php echo $search_txt;?>" style="width: 250px; border: solid 1px #7A7A7A; color:#000;" />
            </label>

            <label for="area">
                <span>Area:</span><br>
                <select id="area" name="area">
                    <option value=""><label>--Select Area--</label></option>
                    <?php
                    foreach($areas as $key=>$val) {
                        ?><option value="<?php echo $key;?>"<?php if($area == $key){echo ' selected';}?>><?php echo $val;?></option><?php
                    }		
                    ?>
                </select>
            </label>

            <label for="building">
                <span>Building:</span><br>
                <select id="building" name="building">
                    <option value=""><label>--Select Building--</label></option>
                    <?php
                    foreach($buildings as $key=>$val) {
                        ?><option value="<?php echo $key;?>"<?php if($building == $key){echo ' selected';}?>><?php echo $val;?></option><?php
                    }       
                    ?>
                </select>
            </label>

        <label for="status">
            <span>Status:</span><br>
            <select id="status" name="status">
                <option value="">--Select Status--</option>
                <?php foreach(Complaint::$complaintAdminStatuses as $key=>$val):?>
                <option value="<?php echo $key;?>"<?php if($key==$status) echo ' selected';?>><?php echo $val;?></option>
                <?php endforeach;?>
            </select>
        </label>
        <label>&nbsp;</label>
        <label>&nbsp;</label>
        <label>&nbsp;</label>
        <label>&nbsp;</label>
        <label for="rank">
            <span>Rank:</span><br>
            <select id="rank" name="rank">
                <option value="">--Select Rank--</option>
                <?php
                foreach($ranks as $key=>$val) {
                    ?><option value="<?php echo $key;?>" <?php if($rank == $key) echo 'selected';?>><?php echo $val;?></option><?php
                }?>
            </select>
        </label>
        <label class="checkbox-inline">
            <br>
            <input type="checkbox"  id="rank_opt" name="rank_opt"<?php if($rank_opt=='1'){echo ' checked';}?> value="1">And above
        </label>
        </div>

        <div class="col-md2" style="font-size: .9em;">
            <label for="date_from">
                <span>Date from</span><br>
                <input  type="text" class="datepicker" id="date_from" name="date_from" value="<?php echo $date_from;?>" style="border: solid 1px #7A7A7A; color:#000;" />
            </label>
            <label for="date_to">
                <span>Date to</span><br>
                <input  type="text" class="datepicker" id="date_to" name="date_to" value="<?php echo $date_to;?>" style="border: solid 1px #7A7A7A; color:#000;" />
            </label>
        <label for="problem_type">
            <span>Complain:</span><br>
            <select id="problem_type" name="problem_type">
                <option value="">--Select Complain--</option>
                <?php
                foreach($problem_types as $key=>$val) {
                    ?><option value="<?php echo $key;?>" <?php if($problem_type == $key) echo 'selected';?>><?php echo $val;?></option><?php
                }?>
            </select>
        </label>
        <label for="support_reason">
            <span>Support Type:</span><br>
            <select id="support_reason" name="support_reason">
                <option value="">--Select Reason--</option>
                <?php
                foreach($support_reasons as $key=>$val) {
                    ?><option value="<?php echo $key;?>" <?php if($support_reason == $key) echo 'selected';?>><?php echo $val;?></option><?php
                }?>
            </select>
        </label>
        <label>
            <br>
            <button type="submit" name="list" class="btn-sm"><span class="glyphicon glyphicon-search"></span> Search</button>
        </label>
        <label>
            <br>
            <button type="submit" name="pdf" class="btn-sm"><span class="glyphicon glyphicon-download-alt"></span> PDF</button>
        </label>
        <?php /*?>
        <div class="btn-group">
            <button class="btn btn-sm">Download</button>
            <button data-toggle="dropdown" class="btn btn-sm dropdown-toggle"><span class="caret"></span></button>
            <ul class="dropdown-menu btn-sm">
                <li><a href="#">PDF</a></li>
            </ul>
        </div>
        <?php */?>
        </div>
    
    <!--</div>-->
</form>
<?php //Utility::pr($data); exit;?>
    <table class="table table-bordered table-striped table-hover data-table">
        <thead>
            <tr style="border-top:1px solid #D9D9D9;">
                <th>SL</th>
                <th>Username</th>
                <th>Rank</th>
                <th>Fullname</th>
                <th>Address <!--(House, Building, Area)--></th>
                <th>Date</th>
                <th>Complain</th>
                <th>Status</th>
                <th>Assistant</th>
                <?php if($is_complain_del_allowed):?><th>&nbsp;</th><?php endif;?>
            </tr>
        </thead>
        <tbody style="font-size:1em;">
            <?php $i=0;?>
            <?php foreach($data as $d):?>
			<?php $background = $d['source']=='app'? ' style="background:#D9EDF7;font-style: italic;"' : '';?>
            <tr <?php echo $background;?> id="tr<?php echo $i;?>">
                <td class="text-right" <?php echo $background;?>>
                    <?php $sl = ($page-1)* $limit+$i+1; echo $sl;?>.
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>"><?php echo $d['username'];?></a>
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>"><?php echo $d['rank'];?></a>
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>"><?php echo trim($d['firstname']. ' '. $d['lastname']);?></a>
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>"><?php echo $d['house_no'].', '.$d['building_name'].', '.$d['area_name'];?></a>
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>">
                        PS: <?php echo Date::niceDateTime5($d['pb_since']);?><br>
                        LT: <?php echo Date::niceDateTime5($d['dtt_mod']);?> <br>
						<?php if(!empty($d['dtt_mod'])):?>
						<small><b><?php echo Date::duration($d['dtt_mod'], $d['pb_since']);?></b></small>
						<?php endif;?>
                    </a>
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>"><?php echo $d['pb_title'];?></a>
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>"><?php echo isset(Complaint::$complaintAdminStatuses[$d['id_status']]) ? Complaint::$complaintAdminStatuses[$d['id_status']] : '';
                    if(!empty($d['support_reason'])){
                        echo '<br>(<i>'.$d['support_reason'].'</i>)';
                    }?></a>
                </td>
                <td <?php echo $background;?>>
                    <a href="<?php echo BASE_URL;?>/complaint/details.php?id=<?php echo $d['id'];?>"><?php echo trim($d['assist_fisrtname'].' '.$d['assist_lastname']);?></a>
                </td>
                <?php if($is_complain_del_allowed):?>
                <td><a href="javascript:void(0)" onclick="delete_conf(<?php echo $d['id'];?>, 'tr<?php echo $i;?>')" title="Delete Complaint" class="text-warning"><i class="fa fa-times"></i></a></td>
                <?php endif;?>
            </tr>
            <?php $i++;?>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php //echo '$total: '. $total;
    //echo '<br>';
    //echo '$url: '. $url;
    ?>           
    <?php echo $paginationStr;?>
            
        </div>
    </div>
</div>



<script>
function delete_conf(id, rid)
{
    var con = confirm('Are you sure to delete complaint?');
    if(!con){
        return false;
    } else{
        //window.location.href = '<?php echo BASE_URL;?>/complaint/dele.php?id='+uid;
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/complaint/dele.php',
            data : {id: id},
            success : function (msg) {
                alert(msg);
                if(msg == 'Complaint deleted successfuly!') {
                    $('tr#'+rid).remove();
                }
            }
        });
    }
}
</script>


<script type="text/javascript">
$(function () {
    $('#datepicker').datepicker({ dateFormat: 'dd-mm-yy' }).val();
//    $('.datepicker').datepicker({
//        format: "dd-mm-yyyy"
//    }).on('changeDate', function (e) {
//        $(this).datepicker('hide');
//    });


//    $('.datepicker').datepicker({
//		defaultDate: "+1w",
//		numberOfMonths: 2,
//		onClose: function( selectedDate ) {
//			$( "#ui-datepicker-2" ).datepicker( "option", "minDate", selectedDate );
//		}
//	});

});
</script>


<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area.php',
            data : {id: $(this).val()},
            success : function (msg) {
                $('#building').html(msg);
            }
        });
    });
});
</script>