<div class="row">
    <div class="col-xs-6">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="GO to Add Problem Type">
                    <a href="problem-type-add.php" style="color: white;">Add Problem Type</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <?php if(empty($data)):?>
                <p><h4 class="text-center">No payment record found!</h4></p>
                <?php else:?>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data as $d): ?>
                            <tr>
                                <td><?php echo $d['name']; ?></td>
                                <td class="text-center"><a href="problem-type-update.php?id=<?php echo $d['id'];?>">Edit</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>