<?php 
$tr_class = [
    0 => 'text-muted',
    1 => '',
];
$active_status = [
    0 => 'Inactive',
    1 => 'Active',
];
?>
<div class="row">
    <div class="col-xs-6">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Go to Add Support Type">
                    <a href="support-type-add.php" style="color: white;">Add Support Type</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <?php if(empty($support_types)):?>
                <p><h4 class="text-center">No record found!</h4></p>
                <?php else:?>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($support_types as $key=>$val): ?>
                            <tr class="<?php echo $tr_class[ ($val['is_active']%2) ];?>">
                                <td><?php echo $val['name']; ?></td>
                                <td><?php echo $active_status[ ($val['is_active']%2) ]; ?></td>
                                <td class="text-center"><a href="support-type-update.php?id=<?php echo $key;?>">Edit</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>
