<?php //Utility::pr($data);?>

<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Back to Building List Page">
                    <a href="support-in-charge.php" style="color: white;">List</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="" name="user_inpt_frm" id="user_inpt_frm">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label">Area</label>
                        <div class="col-sm-4 col-md-4 col-lg-5">
                            <input type="text" class="form-control input-sm" value="<?php echo $data['area'];?>" readonly />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="uid">Assigned Person</label>
						<?php 
						//echo '<pre>';var_export($supports_in_charge); exit;
						?>
                        <div class="col-sm-4 col-md-4 col-lg-5<?php if(isset($errors['uid'])){echo ' has-error';}?>">
                            <select name="uid" id="uid" class="form-control input-sm">
                                <option value=""></option>
                                <?php foreach($supports_in_charge as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$data['uid']){echo 'selected';}?>><?php echo $val['name'].' ('.$val['mobile'].')';?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['uid'])):?><span class="help-inline" for="uid_no"><?php echo $errors['uid'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Update" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
