<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Back to Support Types">
                    <a href="support-type.php" style="color: white;">Support Types</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="support-type-update.php?id=<?php echo $id;?>">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="support_type">Problem Type <span style='color:red;'>*</span></label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['support_type'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="support_type" id="support_type" value="<?php echo $support_type;?>" placeholder="Problem Type" autocomplete="off" />
                            <?php if(isset($errors['support_type'])):?><span class="help-inline" for="support_type"><?php echo $errors['support_type'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="is_active">Status <span style='color:red;'>*</span></label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['is_active'])){echo ' has-error';}?>">
                            <label class="radio-inline"><input type="radio" name="is_active"<?php if($is_active=='1'){echo ' checked';}?> value="1"> Enabled</label>
                            <label class="radio-inline"><input type="radio" name="is_active"<?php if($is_active=='0'){echo ' checked';}?> value="0"> Disabled</label>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Update" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>

