<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="" name="add_role_frm" id="add_role_frm">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="role_name">Role Name</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['role_name'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="role_name" id="role_name" value="<?php echo $role_name;?>" placeholder="Role Name" autocomplete="off" />
                            <?php if(isset($errors['role_name'])):?><span class="help-inline" style="color:red; background: yellow; font-weight: bold;" for="role_name"><?php echo $errors['role_name'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label">Role Access</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['acls'])){echo ' has-error';}?>">
                            <?php if(isset($errors['acls'])):?><span class="help-inline" style="color:red; background: yellow; font-weight: bold;"><?php echo $errors['acls'];?></span><?php endif;?>
                            <ul class="raf-ul-nstl ">
                            <?php foreach($roles as $title=>$values):?>
                                <li>
                                    <span><?php echo $title;?></span>
                                    <ul>
                                        <?php foreach($values as $val):?>
                                        <li>
                                            <label class="fnt-nrml">
                                                <input type="checkbox" name="acls[]" value="<?php echo $val['id'];?>" <?php if(in_array($val['id'], $acls)){echo 'checked';}?> /> <?php echo $val['name'];?>
                                            </label>
                                        </li>
                                        <?php endforeach;?>
                                    </ul>
                                </li>
                            <?php endforeach;?>
                            </ul>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                    <?php //Utility::pr($roles);?>
                    <?php //Utility::pr($acls);?>
                </form>
            </div>
        </div>			
    </div>
</div>
