
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-align-justify"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Subscriber List">
                    <a href="index.php" style="color: white;">List</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="add.php" name="subscriber_add_upd" id="subscriber_add_upd">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="username">Username</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['username'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="username" id="username" value="<?php echo $username;?>" placeholder="Username" autocomplete="off" />
                            <?php if(isset($errors['username'])):?><span class="help-inline" for="username"><?php echo $errors['username'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="password">Password</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['password'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="password" id="password" value="<?php echo $password;?>" placeholder="Password" autocomplete="off" />
                            <?php if(isset($errors['password'])):?><span class="help-inline" for="password"><?php echo $errors['password'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="ba_no">BA No</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['ba_no'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="ba_no" id="ba_no" value="<?php echo $ba_no;?>" placeholder="BA NO" autocomplete="off" />
                            <?php if(isset($errors['ba_no'])):?><span class="help-inline" for="ba_no"><?php echo $errors['ba_no'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="firstname">Full Name</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['firstname'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4">
                                    Firstname
                                    <input type="text" class="form-control input-sm" name="firstname" id="firstname" value="<?php echo $firstname;?>" placeholder="Firstname" autocomplete="off" />
                                    <?php if(isset($errors['firstname'])):?><span class="help-inline" for="firstname"><?php echo $errors['firstname'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['lastname'])){echo ' has-error';}?>">
                                    Lastname
                                    <input type="text" class="form-control input-sm" name="lastname" id="lastname" value="<?php echo $lastname;?>" placeholder="Lastname" autocomplete="off" />
                                    <?php if(isset($errors['lastname'])):?><span class="help-inline" for="lastname"><?php echo $errors['lastname'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="rank">Rank</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['rank'])){echo ' has-error';}?>">
                            <select name="rank" id="rank" class="form-control input-sm">
                                <option value="">-- SELECT RANK --</option>
                                <?php foreach($ranks as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$rank){echo 'selected';}?>><?php echo $val;?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['rank'])):?><span class="help-inline" for="rank"><?php echo $errors['rank'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="area">Address</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['area']) || isset($errors['building']) || isset($errors['house_no']) || isset($errors['remote_ip'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-3">
                                    Area:
                                    <select name="area" id="area" class="form-control input-sm">
                                        <option value="">-- SELECT AREA --</option>
                                        <?php foreach($areas as $key=>$val):?>
                                        <option value="<?php echo $key;?>" <?php if($key==$area){echo 'selected';}?>><?php echo $val;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['area'])):?><span class="help-inline" for="area"><?php echo $errors['area'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['road_no'])){echo ' has-error';}?>">
                                    Building:
                                    <select name="building" id="building" class="form-control input-sm">
                                        <option value="">-- SELECT BUILDING --</option>
                                        <?php foreach($buildings as $key=>$val):?>
                                        <option value="<?php echo $key;?>" <?php if($key==$building){echo 'selected';}?>><?php echo $val;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['building'])):?><span class="help-inline" for="building"><?php echo $errors['building'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['house_no'])){echo ' has-error';}?>">
                                    House no:
                                    <input type="text" class="form-control input-sm" name="house_no" id="house_no" value="<?php echo $house_no;?>" placeholder="House No" autocomplete="off" />
                                    <?php if(isset($errors['house_no'])):?><span class="help-inline" for="house_no"><?php echo $errors['house_no'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['road_no'])){echo ' has-error';}?>">
                                    Remote IP:
                                    <select name="remote_ip" id="remote_ip" class="form-control input-sm">
                                        <option value="">-- SELECT REMOTE IP --</option>
                                        <?php foreach($remote_ips as $ip):?>
                                        <option value="<?php echo $ip;?>" <?php if($ip==$remote_ip){echo 'selected';}?>><?php echo $ip;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['remote_ip'])):?><span class="help-inline" for="remote_ip"><?php echo $errors['remote_ip'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="official_mobile">Mobile</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['official_mobile'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4">
                                    Official Mobile Number
                                    <input type="text" class="form-control input-sm" name="official_mobile" id="official_mobile" value="<?php echo $official_mobile;?>" placeholder="Official Mobile Number" autocomplete="off" />
                                    <?php if(isset($errors['official_mobile'])):?><span class="help-inline" for="official_mobile"><?php echo $errors['official_mobile'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['personal_mobile'])){echo ' has-error';}?>">
                                    Personal Mobile Number
                                    <input type="text" class="form-control input-sm" name="personal_mobile" id="personal_mobile" value="<?php echo $personal_mobile;?>" placeholder="Personal Mobile Number" autocomplete="off" />
                                    <?php if(isset($errors['personal_mobile'])):?><span class="help-inline" for="personal_mobile"><?php echo $errors['personal_mobile'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['residential_phone'])){echo ' has-error';}?>">
                                    Residential Phone Number
                                    <input type="text" class="form-control input-sm" name="residential_phone" id="residential_phone" value="<?php echo $residential_phone;?>" placeholder="Residential Phone Number" autocomplete="off" />
                                    <?php if(isset($errors['residential_phone'])):?><span class="help-inline" for="residential_phone"><?php echo $errors['residential_phone'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="email">Email</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['email'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="email" id="email" value="<?php echo $email;?>" autocomplete="off" />
                            <?php if(isset($errors['email'])):?><span class="help-inline" for="email"><?php echo $errors['email'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="package">Connection Package</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['package'])){echo ' has-error';}?>">
                            <select name="package" id="package" class="form-control input-sm">
                                <option value="">-- SELECT PACKAGE --</option>
                                <?php foreach($packages as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$package){echo 'selected';}?>><?php echo $val['name'];?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['package'])):?><span class="help-inline" for="package"><?php echo $errors['package'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="category">Subscriber Category</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['category'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-3">
                                    Category                                    
                                    <select name="category" id="category" class="form-control input-sm">
                                        <option value="">-- SELECT CATEGORY --</option>
                                        <?php foreach($subscriber_categories as $scat):?>
                                        <option value="<?php echo $scat;?>" <?php if($scat==$category){echo 'selected';}?>><?php echo $scat;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['category'])):?><span class="help-inline" for="category"><?php echo $errors['category'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['complementary_amount'])){echo ' has-error';}?><?php if($category!='Complementary'){echo ' disp-off';}?>" id="compl-amt-blk">
                                    Complementary Amount
                                    <input type="text" class="form-control input-sm" name="complementary_amount" id="complementary_amount" value="<?php echo $complementary_amount;?>" placeholder="Complementary Amount" autocomplete="off" />
                                    <?php if(isset($errors['complementary_amount'])):?><span class="help-inline" for="complementary_amount"><?php echo $errors['complementary_amount'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="remarks">Remarks</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['remarks'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-12">
                                    <textarea class="form-control input-sm" name="remarks" id="remarks"placeholder="Remarks"><?php echo $remarks;?></textarea>
                                    <?php if(isset($errors['remarks'])):?><span class="help-inline" for="remarks"><?php echo $errors['remarks'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Create" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area.php',
            data : {id: $(this).val()},
            success : function (msg) {
                        $('#building').html(msg);
                        $('#remote_ip').html('<option value="">-- SELECT REMOTE IP --</option>');
                    }
        });
    });
    
    $('#building').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-remote-ip-by-building.php',
            data : {id: $(this).val()},
            success : function (msg) {
                        $('#remote_ip').html(msg);
                    }
        });
    });
});
</script>