<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="fa fa-align-justify"></i></span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Edit Subscriber">
                    <a href="update.php?id=<?php echo $id;?>" style="color: white;">Edit</a>
                </span>
            </div>
<!--            <div class="widget-title">
                <span class="icon"><i class="fa fa-comment"></i></span><h5>Recent Comments</h5>
                <span title="" class="label label-info tip-left" data-original-title="88 total comments">88</span>
            </div>-->
            <div class="widget-content" id="prnta">
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Username</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['username'];?></div>
                   <div class="col-sm-2 raf-lft">Password</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['password'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">BA No.</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $data['ba_no'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Full Name</div>
                   <div class="col-sm-10 raf-rgt"><?php echo trim($data['firstname'].' '.$data['lastname']);?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Rank</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $data['rank'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Area</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['area'];?></div>
                   <div class="col-sm-2 raf-lft">Building</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['building'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">House</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['house_no'];?></div>
                   <div class="col-sm-2 raf-lft">Remote IP</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['remote_ip'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Official Mobile</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['official_mobile'];?></div>
                   <div class="col-sm-2 raf-lft">Personal Mobile</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['personal_mobile'];?></div>
                   <div class="col-sm-2 raf-lft">Residential Phone</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['residential_phone'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Email</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $data['email'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Package</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $data['package'];?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Category</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['category'];?></div>
                   <?php if($data['category']=='Complementary'):?>
                   <div class="col-sm-2 raf-lft">Complementary Amount</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['complementary_amount'];?></div>
                   <?php endif;?>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Current Balance</div>
                   <div class="col-sm-2 raf-rgt"><?php echo $data['payment_balance'];?></div>
                   <div class="col-sm-2 raf-lft">Status</div>
                   <div class="col-sm-2 raf-rgt"><?php echo Subscriber::getStatus($data['status_id']);?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Connection From</div>
                   <div class="col-sm-2 raf-rgt"><?php echo Date::niceDateTime($data['connection_from']);?></div>
                   <div class="col-sm-2 raf-lft">Connection To</div>
                   <div class="col-sm-2 raf-rgt"><?php echo Date::niceDateTime($data['connection_to']);?></div>
                </div>
                <div class="clearfix bbtm">
                   <div class="col-sm-2 raf-lft">Remarks</div>
                   <div class="col-sm-9 raf-rgt"><?php echo $data['remarks'];?></div>
                </div>
            </div>
            <!-- <input type='button' value='Print' id='print_button2' /> -->
            <!-- <div><center>
               <button class="btn btn-primary hidden-print" id="print_button2"><span class="glyphicon glyphicon-print" aria-hidden="true"></span> Print</button>
            </center></div> -->

          <div><center>
            <form method="post" action=""> 
            <button type="submit" name="pdf" class="btn btn-primary"><span class="glyphicon glyphicon-download-alt"></span> PDF export</button>
            </form>
          </center></div>
          <br style="clear:both;" />
        </div>
    </div>
</div>

<!-- <script>
  $(document).ready(function(){
      $("#print_button2").click(function(){
        var mode = 'iframe';
        var close = mode == "popup";
        var options = {mode : mode, popClose : close};
      //$("#test1").attr("visibility", "visible");
        $("div#prnta").printArea( options );
    });   
  });
</script> -->