<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5>Subscribers</h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Add New Subscriber">
                    <a href="add.php" style="color: white;">Add</a>
                </span>
                <!--<a class="btn btn-primary btn-xs" href="add.php" style="margin-top: 5px; margin-right: 5px; float:right;">&laquo; Add new subscriber</a>-->
            </div>
            <div class="widget-content nopadding">
                <form action="index.php" method="get">
                <div class="row" style="font-size:.8em; margin-bottom: 20px;">
                    <div class="col-md-2">
                        BA / User Id:
                        <input type="text" class="form-control input-sm" name="ba" id="str" value="<?php echo $ba;?>" placeholder="" autocomplete="off" />
                    </div>
                    <div class="col-md-2">
                        Name / Mobile:
                        <input type="text" class="form-control input-sm" name="str" id="str" value="<?php echo $str;?>" placeholder="" autocomplete="off" />
                    </div>
                    <div class="col-md-2">
                        Rank:
                        <select name="rank" id="rank" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($ranks as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$rank){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        Area:
                        <select name="area" id="area" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($areas as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$area){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        Building:
                        <select name="bld" id="bld" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($buildings as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$bld){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        House:
                        <input type="text" class="form-control input-sm" name="house" id="srch_key" value="<?php echo $house;?>" placeholder="" autocomplete="off" />
                    </div>
                    <div class="col-md-2">
                        Category:
                        <select name="cat" id="cat" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($categories as $category):?>
                            <option value="<?php echo $category;?>" <?php if($category==$cat){echo 'selected';}?>><?php echo $category;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        Package:
                        <select name="pkg" id="pkg" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($packages as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$pkg){echo 'selected';}?>><?php echo $val['name'];?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        Status:
                        <select name="sts" id="sts" class="form-control input-sm">
                            <option value="-1"></option>
                            <?php foreach($statuses as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$sts){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        &nbsp;<br>
                        <button class="btn btn-success btn-sm"><span class="icon"><i class="fa fa-search"></i> </span> Search</button>
                    </div>
                </div>
                </form>
                <!--table-nonfluid-->
                <?php 
                $tr_class = [
                    0 => 'text-muted',
                    1 => 'text-success',
                    //1 => '',
                    2 => 'text-danger',
                ];
                ?>
                <?php //echo $paginationStr;?>
                <table class="table table-bordered table-striped table-hover data-table">
                    <thead>
                        <tr style="border-top:1px solid #D9D9D9;">
<!--                            <th style="width:62px; text-align:right;">
                                <input type="checkbox" name="chk_all" id="chk_all" value="1" />
                            </th>-->
                            <th>SL</th>
                            <th>User Id</th>
                            <th>Rank</th>
                            <th>Name</th>
                            <th>Address (House, Building, Area)</th>
                            <th>Mobile</th>
                            <th>Balance</th>
                            <th>Package</th>
                            <th>Category</th>
                            <th>Status</th>
                            <th style="width:65px;">Action</th>                            
                        </tr>
                    </thead>
                    <tbody style="font-size:.80em;">
                    <?php $i=0;?>
                    <?php foreach($subscribers as $sub):?>
                        <tr class="<?php echo $tr_class[ $sub['status_id'] ];?>">
                            <td class="text-right">
                                <?php $sl = ($page-1)*LIMIT_PER_PAGE + ++$i; echo $sl;?>.
<!--                                <input type="checkbox" name="chk_indv" id="chk_indv_<?php echo $sl;?>" class="chk_indv" value="1" />-->
                            </td>
                        <td><?php echo $sub['username'];?></td>
                        <td><?php echo $sub['rank'];?></td>
                        <td><?php echo trim($sub['firstname'].' '.$sub['lastname']);?></td>
                        <td><?php echo $sub['house_no'].', '.$sub['building'].', '.$sub['area'];?></td>
                        <td><?php echo $sub['official_mobile'];?></td>
                        <td class="text-right"><?php echo $sub['payment_balance'];?></td>
                        <td><?php echo isset($packages[$sub['package_id']]['name']) ? $packages[$sub['package_id']]['name'] : '';?></td>
                        <td><?php echo $sub['category'];?></td>
                        <td><?php echo isset($subscriber_statuses[$sub['status_id']]) ? $subscriber_statuses[$sub['status_id']] : '';?></td>
                        <td class="text-right">
                            <a href="<?php echo BASE_URL.'/subscriber/detail.php?id='.$sub['id'];?>" title="View Details" class="text-success"><i class="fa fa-eye"></i></a> | 
                            <a href="<?php echo BASE_URL.'/subscriber/update.php?id='.$sub['id'];?>" title="Edit Subscriber" class="text-primary"><i class="fa fa-edit"></i></a>
                            <?php /*if($sub['status_id'] != 2):?>
                            <a href="javascript:void(0)" onclick="delete_conf(<?php echo $sub['id'];?>, '<?php echo $sub['username'];?>')" title="Delete Subscriber" class="text-warning"><i class="fa fa-times"></i></a>
                            <?php endif;*/?>
                        </td>
                    </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
                <?php echo $paginationStr;?>
            </div>
        </div>
    </div>
</div>


<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area.php',
            data : {id: $(this).val()},
            success : function (msg) {
                        $('#bld').html(msg);
                    }
        });
    });
});

function delete_conf(sid, username)
{
    var con = confirm('Are you sure to delete username "'+username+'"?');
    if(!con){
        return false;
    } else{
        window.location.href = '<?php echo BASE_URL;?>/subscriber/delete.php?id='+sid;
    }
}
</script>