<div class="row">
    <div class="col-xs-10">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
            </div>
            <div class="widget-content nopadding">
                <form action="" method="post">
                <div class="row" style="font-size:.8em; margin-bottom: 20px;">
                    <div class="col-md-3">
                        Area:
                        <select name="area" id="area" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($areas as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$area){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-3">
                        Building:
                        <select name="building" id="building" class="form-control input-sm">
                            <option value=""></option>
                            <?php foreach($buildings as $key=>$val):?>
                            <option value="<?php echo $key;?>" <?php if($key==$building){echo 'selected';}?>><?php echo $val;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="col-md-3" style="font-size: 14px;">
                        <br>
                        Total active subscribers: <span id="tot_act_sbs"><?php echo $total_active_subscibers;?></span>
                    </div>
                </div>
                <div class="row" style="">
                    <div class="col-md-8">SMS<br>
                    <textarea name="sms_text" id="sms_text" title="Write SMS" style="width: 90%;"><?php echo $sms_text;?></textarea>
                    </div>
                </div>
                <div class="row" style="">
                    <div class="col-md-2">
                        <br />
                        <button class="btn btn-success btn-sm">Submit</button>
                    </div>
                </div>
                </form>
                <br>
            </div>
        </div>
    </div>
</div>


<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area-wth-active-subscriber-count.php',
            data : {id: $(this).val()},
            success : function (msg) {
                var [a, b] = msg.split('##');
                $('#building').html(a);
                $('#tot_act_sbs').html(b);
            }
        });
    });
    
    $('#building').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-active-subscriber-count-by-building.php',
            data : {id: $(this).val()},
            success : function (msg) {
                $('#tot_act_sbs').html(msg);
            }
        });
    });
});
</script>