<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="fa fa-th-list"></i>									
                </span>
                <h5><?php echo $pageTitle;?></h5>
                <span title="" class="label label-info tip-left" style="padding:5px;" data-original-title="Subscriber Details page">
                    <a href="detail.php?id=<?php echo $id;?>" style="color: white;">Details</a>
                </span>
            </div>
            <div class="widget-content nopadding">
                <form class="form-horizontal" method="post" action="update.php?id=<?php echo $id;?>" name="subscriber_add_upd" id="subscriber_add_upd">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="username">Username</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['username'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="username" id="username" value="<?php echo $data['username'];?>" placeholder="Username" autocomplete="off" />
                            <?php if(isset($errors['username'])):?><span class="help-inline" for="username"><?php echo $errors['username'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="password">Password</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['password'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="password" id="password" value="<?php echo $data['password'];?>" placeholder="Password" autocomplete="off" />
                            <?php if(isset($errors['password'])):?><span class="help-inline" for="password"><?php echo $errors['password'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="ba_no">BA No</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['ba_no'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="ba_no" id="ba_no" value="<?php echo $data['ba_no'];?>" placeholder="BA NO" autocomplete="off" />
                            <?php if(isset($errors['ba_no'])):?><span class="help-inline" for="ba_no"><?php echo $errors['ba_no'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="firstname">Full Name</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['firstname'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4">
                                    Firstname
                                    <input type="text" class="form-control input-sm" name="firstname" id="firstname" value="<?php echo $data['firstname'];?>" placeholder="Firstname" autocomplete="off" />
                                    <?php if(isset($errors['firstname'])):?><span class="help-inline" for="firstname"><?php echo $errors['firstname'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['lastname'])){echo ' has-error';}?>">
                                    Lastname
                                    <input type="text" class="form-control input-sm" name="lastname" id="lastname" value="<?php echo $data['lastname'];?>" placeholder="Lastname" autocomplete="off" />
                                    <?php if(isset($errors['lastname'])):?><span class="help-inline" for="lastname"><?php echo $errors['lastname'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="rank">Rank</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['rank'])){echo ' has-error';}?>">
                            <select name="rank" id="rank" class="form-control input-sm">
                                <option value="">-- SELECT RANK --</option>
                                <?php foreach($ranks as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$data['rank_id']){echo 'selected';}?>><?php echo $val;?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['rank'])):?><span class="help-inline" for="rank"><?php echo $errors['rank'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="area">Address</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['area']) || isset($errors['building']) || isset($errors['house_no']) || isset($errors['remote_ip'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-3">
                                    Area:
                                    <select name="area" id="area" class="form-control input-sm">
                                        <option value="">-- SELECT AREA --</option>
                                        <?php foreach($areas as $key=>$val):?>
                                        <option value="<?php echo $key;?>" <?php if($key==$data['area_id']){echo 'selected';}?>><?php echo $val;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['area'])):?><span class="help-inline" for="area"><?php echo $errors['area'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['road_no'])){echo ' has-error';}?>">
                                    Building:
                                    <select name="building" id="building" class="form-control input-sm">
                                        <option value="">-- SELECT BUILDING --</option>
                                        <?php foreach($buildings as $key=>$val):?>
                                        <option value="<?php echo $key;?>" <?php if($key==$data['building_id']){echo 'selected';}?>><?php echo $val;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['building'])):?><span class="help-inline" for="building"><?php echo $errors['building'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['house_no'])){echo ' has-error';}?>">
                                    House no:
                                    <input type="text" class="form-control input-sm" name="house_no" id="house_no" value="<?php echo $data['house_no'];?>" placeholder="House No" autocomplete="off" />
                                    <?php if(isset($errors['house_no'])):?><span class="help-inline" for="house_no"><?php echo $errors['house_no'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['road_no'])){echo ' has-error';}?>">
                                    Remote IP:
                                    <select name="remote_ip" id="remote_ip" class="form-control input-sm">
                                        <option value="">-- SELECT REMOTE IP --</option>
                                        <?php foreach($remote_ips as $ip):?>
                                        <option value="<?php echo $ip;?>" <?php if($ip==$data['remote_ip']){echo 'selected';}?>><?php echo $ip;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['remote_ip'])):?><span class="help-inline" for="remote_ip"><?php echo $errors['remote_ip'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="official_mobile">Mobile</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['official_mobile'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4<?php if(isset($errors['official_mobile'])){echo ' has-error';}?>">
                                    Official Mobile Number
                                    <input type="text" class="form-control input-sm" name="official_mobile" id="official_mobile" value="<?php echo $data['official_mobile'];?>" placeholder="Official Mobile Number" autocomplete="off" />
                                    <?php if(isset($errors['official_mobile'])):?><span class="help-inline" for="official_mobile"><?php echo $errors['official_mobile'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['personal_mobile'])){echo ' has-error';}?>">
                                    Personal Mobile Number
                                    <input type="text" class="form-control input-sm" name="personal_mobile" id="personal_mobile" value="<?php echo $data['personal_mobile'];?>" placeholder="Personal Mobile Number" autocomplete="off" />
                                    <?php if(isset($errors['personal_mobile'])):?><span class="help-inline" for="personal_mobile"><?php echo $errors['personal_mobile'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['residential_phone'])){echo ' has-error';}?>">
                                    Residential Phone Number
                                    <input type="text" class="form-control input-sm" name="residential_phone" id="residential_phone" value="<?php echo $data['residential_phone'];?>" placeholder="Residential Phone Number" autocomplete="off" />
                                    <?php if(isset($errors['residential_phone'])):?><span class="help-inline" for="residential_phone"><?php echo $errors['residential_phone'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="email">Email</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['email'])){echo ' has-error';}?>">
                            <input type="text" class="form-control input-sm" name="email" id="email" value="<?php echo $data['email'];?>" autocomplete="off" />
                            <?php if(isset($errors['email'])):?><span class="help-inline" for="email"><?php echo $errors['email'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="package">Connection Package</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['package'])){echo ' has-error';}?>">
                            <select name="package" id="package" class="form-control input-sm">
                                <option value="">-- SELECT PACKAGE --</option>
                                <?php foreach($packages as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if($key==$data['package_id']){echo 'selected';}?>><?php echo $val['name'];?></option>
                                <?php endforeach;?>
                            </select>
                            <?php if(isset($errors['package'])):?><span class="help-inline" for="package"><?php echo $errors['package'];?></span><?php endif;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="category">Subscriber Category</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['category'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-3">
                                    Category                                    
                                    <select name="category" id="category" class="form-control input-sm">
                                        <option value="">-- SELECT CATEGORY --</option>
                                        <?php foreach($subscriber_categories as $scat):?>
                                        <option value="<?php echo $scat;?>" <?php if($scat==$data['category']){echo 'selected';}?>><?php echo $scat;?></option>
                                        <?php endforeach;?>
                                    </select>
                                    <?php if(isset($errors['category'])):?><span class="help-inline" for="category"><?php echo $errors['category'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-3<?php if(isset($errors['complementary_amount'])){echo ' has-error';}?><?php if($data['category'] != 'Complementary'){echo ' disp-off';}?>" id="compl-amt-blk">
                                    Complementary Amount
                                    <input type="text" class="form-control input-sm" name="complementary_amount" id="complementary_amount" value="<?php echo $data['complementary_amount'];?>" placeholder="Complementary Amount" autocomplete="off" />
                                    <?php if(isset($errors['complementary_amount'])):?><span class="help-inline" for="complementary_amount"><?php echo $errors['complementary_amount'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="category">Connectivity</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['category'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-4">
                                    &nbsp;<br>
                                    <label class="fnt-nrml"><input type="radio" name="status_id" value="1"<?php if($data['status_id']=='1'){echo ' checked';}?> /> Active</label> &nbsp;
                                    <label class="fnt-nrml"><input type="radio" name="status_id" value="0"<?php if($data['status_id']=='0'){echo ' checked';}?> /> Suspended</label>
                                    <label class="fnt-nrml"><input type="radio" name="status_id" value="2"<?php if($data['status_id']=='2'){echo ' checked';}?> /> Deleted</label>
                                    <?php if(isset($errors['status_id'])):?><span class="help-inline" for="category"><?php echo $errors['status_id'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['connection_from'])){echo ' has-error';}?>">
                                    Connection from<br>

                                    <?php if(in_array(1, Session::get('user_roles'))){
                                        echo Date::createDropdown(12, 'connection_from_split', 'connection_from_split', '', $data['connection_from_split']['d'],$data['connection_from_split']['m'],$data['connection_from_split']['y'],$data['connection_from_split']['h'],$data['connection_from_split']['i'], $data['connection_from_split']['a'], '<br>', true);
                                    } else{
                                        echo $data['connection_from'];
                                    }?>
                                    <?php if(isset($errors['connection_from'])):?><br><span class="help-inline" for="connection_from_split"><?php echo $errors['connection_from'];?></span><?php endif;?>
                                </div>
                                <div class="col-md-4<?php if(isset($errors['connection_to'])){echo ' has-error';}?>">
                                    Connection to<br>
                                    <?php if(in_array(1, Session::get('user_roles'))){
                                        echo Date::createDropdown(12, 'connection_to_split', 'connection_to_split', '', $data['connection_to_split']['d'],$data['connection_to_split']['m'],$data['connection_to_split']['y'],$data['connection_to_split']['h'],$data['connection_to_split']['i'], $data['connection_to_split']['a'], '<br>', true);
                                    } else{
                                        echo $data['connection_to'];
                                    }?>
                                    <?php if(isset($errors['connection_to'])):?><br><span class="help-inline" for="connection_to_split"><?php echo $errors['connection_to'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="payment_balance">Current Balance</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['payment_balance'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-1">
                                    <?php if(in_array(1, Session::get('user_roles'))){?>
                                    <input type="text" class="form-control input-sm" name="payment_balance" id="payment_balance" value="<?php echo $data['payment_balance'];?>" autocomplete="off" />
                                    <?php } else{
                                    echo $data['payment_balance'];
                                    }?>
                                    
                                    <?php if(isset($errors['payment_balance'])):?><span class="help-inline" for="payment_balance"><?php echo $errors['payment_balance'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 col-lg-2 control-label" for="remarks">Remarks</label>
                        <div class="col-sm-9 col-md-9 col-lg-10<?php if(isset($errors['remarks'])){echo ' has-error';}?>">
                            <div class="row">
                                <div class="col-md-12">
                                    <textarea class="form-control input-sm" name="remarks" id="remarks"placeholder="Remarks"><?php echo $data['remarks'];?></textarea>
                                    <?php if(isset($errors['remarks'])):?><span class="help-inline" for="remarks"><?php echo $errors['remarks'];?></span><?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="hidden" name="<?php echo TOKEN_LEVEL;?>" id="<?php echo TOKEN_LEVEL;?>" value="<?php echo Token::generate(TOKEN_LEVEL);?>">
                        <input type="submit" value="Update" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>			
    </div>
</div>
<script>
$(function() {
    $('#area').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-buildings-by-area.php',
            data : {id: $(this).val()},
            success : function (msg) {
                        $('#building').html(msg);
                        $('#remote_ip').html('<option value="">-- SELECT REMOTE IP --</option>');
                    }
        });
    });
    
    $('#building').on('change', function() {
        $.ajax({
            type : 'POST',
            url  : '<?php echo BASE_URL;?>/modules/ajx/dd-remote-ip-by-building.php',
            data : {id: $(this).val()},
            success : function (msg) {
                        $('#remote_ip').html(msg);
                    }
        });
    });
});
</script>